// SPDX-License-Identifier: LGPL-3.0-or-later
// ICL geom2 demo: raycast a 3D scene into a point cloud
//
// Left panel: 3D scene with several objects
// Right panel: point cloud generated by raycasting through every pixel
//              of the scene camera, using Camera::getViewRay + scene.findObject

#include <icl/qt/Common2.h>
#include <icl/geom2/Scene2.h>
#include <icl/geom2/Scene2MouseHandler.h>
#include <icl/geom2/GroupNode.h>
#include <icl/geom2/SphereNode.h>
#include <icl/geom2/CuboidNode.h>
#include <icl/geom2/CylinderNode.h>
#include <icl/geom2/ConeNode.h>
#include <icl/geom2/MeshNode.h>
#include <icl/geom2/LightNode.h>
#include <icl/geom2/PointCloud.h>
#include <icl/geom2/PointCloudNode.h>
#include <icl/geom/Camera.h>
#include <icl/geom/Material.h>
#include <icl/utils/Time.h>

using namespace icl::geom2;
using namespace icl::geom;
using namespace icl::utils;
using namespace icl::qt;

GUI gui;
Scene2 sceneLeft;   // the "world" scene
Scene2 sceneRight;  // the point cloud viewer

std::shared_ptr<PointCloud> cloud;
std::shared_ptr<PointCloudNode> cloudNode;

// Raycast resolution (lower = faster)
static const int RC_W = 320;
static const int RC_H = 240;

void buildScene() {
  // Red sphere
  auto sphere = SphereNode::create(0, 0, 60, 50, 40, 40);
  sphere->setMaterial(Material::fromColor(GeomColor(220, 60, 60, 255)));
  sphere->getMaterial()->roughness = 0.3f;
  sceneLeft.addNode(sphere);

  // Blue cube
  auto cube = CuboidNode::create(120, 80, 30, 60, 60, 60);
  cube->setMaterial(Material::fromColor(GeomColor(60, 60, 220, 255)));
  cube->getMaterial()->metallic = 0.5f;
  sceneLeft.addNode(cube);

  // Green cylinder
  auto cyl = CylinderNode::create(-100, 80, 40, 30, 30, 80, 30);
  cyl->setMaterial(Material::fromColor(GeomColor(60, 200, 60, 255)));
  sceneLeft.addNode(cyl);

  // Yellow cone
  auto cone = ConeNode::create(-60, -100, 30, 40, 40, 60, 20);
  cone->setMaterial(Material::fromColor(GeomColor(240, 200, 40, 255)));
  sceneLeft.addNode(cone);

  // Ground plane
  auto ground = std::make_shared<MeshNode>();
  float gs = 250;
  ground->addVertex(Vec(-gs, -gs, 0, 1));
  ground->addVertex(Vec(gs, -gs, 0, 1));
  ground->addVertex(Vec(gs, gs, 0, 1));
  ground->addVertex(Vec(-gs, gs, 0, 1));
  ground->addQuad(0, 1, 2, 3);
  ground->createAutoNormals(false);
  ground->setMaterial(Material::fromColor(GeomColor(180, 180, 180, 255)));
  sceneLeft.addNode(ground);

  // Extra spheres
  srand(42);
  for (int i = 0; i < 20; i++) {
    float x = (rand() % 400) - 200;
    float y = (rand() % 400) - 200;
    float z = 20 + (rand() % 80);
    float r = 15 + (rand() % 25);
    auto s = SphereNode::create(x, y, z, r, 20, 20);
    GeomColor c(40 + rand()%200, 40 + rand()%200, 40 + rand()%200, 255);
    s->setMaterial(Material::fromColor(c));
    s->getMaterial()->roughness = 0.2f + (rand() % 60) / 100.0f;
    sceneLeft.addNode(s);
  }

  // Light
  auto light = std::make_shared<LightNode>(LightNode::Point);
  light->setColor(GeomColor(1.0f, 0.97f, 0.92f, 1.0f));
  light->setIntensity(1.5f);
  light->translate(200, 150, 300);
  sceneLeft.addLight(light);
}

void raycastScene() {
  int stepX = sceneLeft.getCamera(0).getResolution().width / RC_W;
  int stepY = sceneLeft.getCamera(0).getResolution().height / RC_H;
  cloud->lock();
  sceneLeft.buildBVH().raycastImage(sceneLeft.getCamera(0), *cloud, stepX, stepY);
  cloud->unlock();
}

void init() {
  // Scene camera
  sceneLeft.addCamera(Camera::lookAt(
      Vec(400, -300, 300, 1),
      Vec(0, 0, 30, 1),
      Vec(0, 0, 1, 1),
      Size(640, 480), 60.0f));
  sceneLeft.setBounds(500);

  buildScene();

  // Point cloud viewer camera (same initial view)
  sceneRight.addCamera(Camera::lookAt(
      Vec(400, -300, 300, 1),
      Vec(0, 0, 30, 1),
      Vec(0, 0, 1, 1),
      Size(640, 480), 60.0f));
  sceneRight.setBounds(500);

  // Add a light to the right scene too (for visual consistency)
  auto light2 = std::make_shared<LightNode>(LightNode::Point);
  light2->setColor(GeomColor(1.0f, 1.0f, 1.0f, 1.0f));
  light2->setIntensity(1.5f);
  light2->translate(200, 150, 300);
  sceneRight.addLight(light2);

  // Create point cloud
  cloud = std::make_shared<PointCloud>(RC_W, RC_H,
      PointCloud::XYZ | PointCloud::RGBA32f);
  cloudNode = PointCloudNode::create(cloud);
  cloudNode->setPointSize(3.0f);
  sceneRight.addNode(cloudNode);

  // Do initial raycast
  Time t = Time::now();
  raycastScene();
  t.showAge("initial raycast");

  // GUI: two 3D canvases side by side
  gui << (HBox()
    << Canvas3D(Size(640, 480)).handle("left").label("Scene")
    << Canvas3D(Size(640, 480)).handle("right").label("Point Cloud"))
    << Fps().handle("fps")
    << Show();

  gui["left"].link(sceneLeft.getGLCallback(0).get());
  gui["left"].install(sceneLeft.getMouseHandler(0));

  gui["right"].link(sceneRight.getGLCallback(0).get());
  gui["right"].install(sceneRight.getMouseHandler(0));
}

void run() {
  raycastScene();
  gui["left"].render();
  gui["right"].render();
  gui["fps"].render();
}

int main(int argc, char **argv) {
  return ICLApp(argc, argv, "", init, run).exec();
}
