icl_check_external_package(IPP ipp.h "libippi.dylib;libippcore.dylib" Libraries include _/opt/intel/Compiler/11.1/080/Frameworks/ipp HAVE_IPP_COND TRUE)
if(HAVE_IPP_COND)
  if(ICL_VAR_USE_INTEL_OMP_IF_POSSIBLE)
    set(IPP_LIBS_l ippcore ippi ipps ippcv ippm ippcc guide iomp5 )
  else()
    set(IPP_LIBS_l ippcore ippi ipps ippcv ippm ippcc)
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /lib/i386-linux-gnu/libpthread.so.0")
  endif()
endif()
