# ICL physics2 - demos

if _build_demos and bullet_found and qt_found
  executable('physics2-scene-demo',
    files('../demos/physics2-scene.cpp'),
    dependencies: [icl_physics2_dep],
    install: false,
  )
  executable('physics2-tilt-demo',
    files('../demos/physics2-tilt.cpp'),
    dependencies: [icl_physics2_dep],
    install: false,
  )
  executable('physics2-cloth-demo',
    files('../demos/physics2-cloth.cpp'),
    dependencies: [icl_physics2_dep],
    install: false,
  )
  executable('physics2-paper-demo',
    files('../demos/physics2-paper.cpp'),
    dependencies: [icl_physics2_dep],
    install: false,
  )
  executable('physics2-constraints-demo',
    files('../demos/physics2-constraints.cpp'),
    dependencies: [icl_physics2_dep],
    install: false,
  )
  executable('physics2-driving-demo',
    files('../demos/physics2-driving.cpp'),
    dependencies: [icl_physics2_dep],
    install: false,
  )
  executable('physics2-maze-demo',
    files('../demos/physics2-maze.cpp'),
    dependencies: [icl_physics2_dep],
    install: false,
  )
endif
