#!/usr/bin/perl

use strict;
use Data::Dumper;

my ($projectName, $majVer, $minVer);
my @content;
my $projectRootName = $ARGV[0];

#------------------
#Get version number
#------------------
open(FILE,"../makeVar") or die "Can not open file: $!";
@content = <FILE>;
close(FILE);

foreach my $line(@content) {
    if ($line =~ /^TARGET_MAJVERSION:= (\d+)/) {
        $majVer = $1;
    }
    
    if ($line =~ /^TARGET_MINVERSION:= (\d+)/) {
        $minVer = $1;
    }   
}

#---------------------------
#Walk through directory tree
#---------------------------
opendir(DIR,"..") or die "Can not open DIR: $!";
my @dirs = readdir(DIR);
closedir(DIR);

my $INSTALLDIR="$ENV{AGNI_LOCAL_ROOT}/${projectRootName}/${majVer}.${minVer}";

#---- Remove old install tree before installing the new one ----
print "---- Remove docs in: $INSTALLDIR/doc \n";
system "rm -R $INSTALLDIR/doc/*";

#---- Install new library----
if (!-e "$INSTALLDIR"){
    print "make dir: $INSTALLDIR\n";
    system "mkdir -p $INSTALLDIR";
    }

if (!-e "$INSTALLDIR/doc"){
    print "make dir: $INSTALLDIR/doc\n";
    system "mkdir $INSTALLDIR/doc";
    }

foreach my $entry(@dirs) {
    if ($entry !~ /^\./ ){        
        if (opendir(DIR,"../".$entry)) {
            while (my $subentry=readdir(DIR)) {
                if ($subentry eq 'doc'){
                    if (!-e "$INSTALLDIR/doc/$entry"){                   
                        ($projectName) = $entry =~ /.*\/(.+?)$/;
                        if (!$projectName) {
                            $projectName = $entry;
                        }
                        system "mkdir $INSTALLDIR/doc/$projectName";
                    }
                    print "---- Copying documentation: $entry/$subentry\n";
                    system "cp -r ../$entry/$subentry/documentation/* $INSTALLDIR/doc/$entry";
                }
                elsif ($subentry !~ /^\./ ){
                    push(@dirs,"$entry/$subentry");
                }
            }
            closedir (DIR);
        }
    }
}

#---------------------
# Remove all .svn dirs
#---------------------
system "find $INSTALLDIR -name '.svn' -exec rm -Rf {} \\; 2> /dev/null";
