#
#   makefile
#

# Don't change anything in this file!
###############################################################################

# Do not assign anything to this variable
_DOT_DOT=

ifeq "${_CURR_DIR}" ""
 _CURR_DIR=.
endif

PROJECT_NAME:= $(notdir $(shell cd ..;pwd))

#-----------------------------------------------
# Rule: all
#-----------------------------------------------
all: install

#-----------------------------------------------
# Rule: installProj
#-----------------------------------------------
install:
	echo "**** Installing Project ****"
	./Install

#-----------------------------------------------
# Rule: % (default rule)
# Note: This rule must be the last one!
#-----------------------------------------------
%: ;
































