# -*-mode: Makefile;-*-  ;; Have EMACS always use makefile-mode for this file. 
#
#   makefile
#

# Don't change anything in this file!
###############################################################################

# Do not assign anything to this variable
_DOT_DOT=

ifeq "${_CURR_DIR}" ""
 _CURR_DIR=.
endif

include ../makeVar

#-----------------------------------------------
# Rule: all
#-----------------------------------------------
all: install

#-----------------------------------------------
# Rule: installProj
#-----------------------------------------------
install:
	echo "**** Installing Project: ${PROJECT_ROOT_NAME} ****"
	./Install ${PROJECT_ROOT_NAME}

#-----------------------------------------------
# Rule: % (default rule)
# Note: This rule must be the last one!
#-----------------------------------------------
%: ;
































