# -*-mode: Makefile;-*-  ;; Have EMACS always use makefile-mode for this file. 
#
#   makefile.doc: creating documentation
#

# Don't change anything in this file!
###############################################################################

# Do not assign anything to this variable
_DOT_DOT=

ifeq "${_CURR_DIR}" ""
 _CURR_DIR=.
endif

PROJECT_NAME:= $(notdir $(shell cd ..;pwd))

include makeVar

#-----------------------------------------------
# Rule: all & cleanall & clean & printtype
#-----------------------------------------------
all: doc

cleanall: cleandoc

clean: cleanall

printtype:
	${PRE_CMD}${CMD_ECHO} "Type: MakeDocumentation"

#-----------------------------------------------
# Rule: doc & cleandoc
#-----------------------------------------------
doc: ${MAKE_PRECOND} _doc_Build ${MAKE_POSTCOND}

_doc_Build:
	${PRE_CMD}${CMD_ECHO} "Building documentation from: ${_CURR_DIR}"
	${PRE_CMD}${CMD_DOCC}
	${PRE_CMD}${CMD_FINAL}

cleandoc: _cleandoc_First ${MORE_CLEAN}

_cleandoc_First:
	${PRE_CMD}${CMD_ECHO} "Cleaning documentation from: ${_CURR_DIR}"
	${PRE_CMD}${CMD_RMDIR} documentation
	${PRE_CMD}${CMD_RM} *~ *.bak

#-----------------------------------------------
# Rule: % (default rule)
# Note: This rule must be the last one!
#-----------------------------------------------
%: ;































