######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 22 20:34:40 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += create_combinations.cpp \
show_arglists.cpp \
main.cpp
