// SPDX-License-Identifier: LGPL-3.0-or-later
// ICL - Image Component Library (https://github.com/iclcv/icl)
// Copyright (C) 2006-2026 Christof Elbrechter

#include <icl/viz3d/render/detail/FilamentRenderBackend.h>

#include <icl/viz3d/nodes/GroupNode.h>
#include <icl/viz3d/nodes/GeometryNode.h>
#include <icl/viz3d/nodes/LightNode.h>
#include <icl/viz3d/nodes/TextNode.h>
#include <icl/viz3d/render/Material.h>
#include <icl/viz3d/render/Sky.h>
#include <icl/utils/prop/Constraints.h>

#include <filament/Camera.h>
#include <filament/ColorGrading.h>
#include <filament/Engine.h>
#include <filament/IndexBuffer.h>
#include <filament/IndirectLight.h>
#include <filament/LightManager.h>
#include <filament/Material.h>
#include <filament/MaterialInstance.h>
#include <filament/RenderableManager.h>
#include <filament/Renderer.h>
#include <filament/Scene.h>
#include <filament/Skybox.h>
#include <filament/SwapChain.h>
#include <filament/Texture.h>
#include <filament/TextureSampler.h>
#include <filament/ToneMapper.h>
#include <filament/TransformManager.h>
#include <filament/VertexBuffer.h>
#include <filament/View.h>
#include <filament/Viewport.h>
#include <filament/Box.h>

#include <geometry/SurfaceOrientation.h>

#include <backend/PixelBufferDescriptor.h>
#include <math/mat4.h>
#include <math/quat.h>
#include <math/vec2.h>
#include <math/vec3.h>
#include <utils/EntityManager.h>

#include <algorithm>
#include <atomic>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <unordered_map>
#include <vector>

// Compiled materials (matc -f header, generated by meson into builddir/icl/viz3d/).
// Referenced build-root-relative so they resolve via the always-present `-I.`
// (builddir root) without adding an include dir — adding ../icl/viz3d would shadow
// Cycles' `#include "scene/scene.h"` on the case-insensitive macOS FS
// (→ icl/viz3d/scene/Scene.h).
static const uint8_t LIT_PBR_FILAMAT[] = {
#include "icl/viz3d/lit_pbr.filamat.h"
};
static const uint8_t UNLIT_SOLID_FILAMAT[] = {
#include "icl/viz3d/unlit_solid.filamat.h"
};

namespace icl::viz3d {

  // NB: do NOT `using namespace filament` here — filament has math::/Scene/
  // Material/Camera that would collide with icl::math / icl::viz3d::Scene /
  // icl::viz3d::Material / icl::cv3d::Camera. Everything Filament is qualified.
  namespace fl = filament;
  namespace flm = filament::math;
  namespace fgeo = filament::geometry;

  namespace {
    // ICL row-major Mat -> Filament column-major mat4.
    flm::mat4 toFilament(const Mat &m) {
      flm::mat4 f;  // identity
      for (int c = 0; c < 4; ++c)
        for (int r = 0; r < 4; ++r)
          f[c][r] = m(r, c);
      return f;
    }

    flm::float3 normalized(flm::float3 v) {
      float l = std::sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
      return l > 1e-8f ? flm::float3{v[0] / l, v[1] / l, v[2] / l} : flm::float3{0, 0, 1};
    }

    // ICL colours are sRGB (display) values; Filament material/light colours are
    // LINEAR. Without this, mixed channels wash out (Filament re-encodes sRGB on
    // output) — e.g. (220,60,60) → milky pink; pure primaries (0/1) are unaffected.
    float srgbToLinear(float s) {
      return s <= 0.04045f ? s / 12.92f : std::pow((s + 0.055f) / 1.055f, 2.4f);
    }
    flm::float3 toLinear(const cv3d::GeomColor &c) {
      return {srgbToLinear(c[0]), srgbToLinear(c[1]), srgbToLinear(c[2])};
    }

    // One Filament renderable (a single primitive topology of a node).
    struct Prim {
      fl::VertexBuffer *vb = nullptr;
      fl::IndexBuffer *ib = nullptr;
      fl::MaterialInstance *mi = nullptr;
      ::utils::Entity entity;    // renderable; also carries a transform component
      bool inScene = false;
    };

    // Per-node Filament geometry (solid mesh + wireframe lines), keyed on the
    // node's geometry version. Points/point-clouds are a later sub-step.
    struct NodeCache {
      Prim solid;                     // triangles + quads (lit PBR)
      std::vector<Prim> lineGroups;   // one LINES renderable per distinct colour
      uint64_t builtVersion = ~0ull;
    };
  }

  struct FilamentRenderBackend::Data {
    fl::Engine *engine = nullptr;
    fl::SwapChain *swapChain = nullptr;
    fl::Renderer *renderer = nullptr;
    fl::View *view = nullptr;
    fl::Scene *fscene = nullptr;
    fl::Camera *fcam = nullptr;
    ::utils::Entity camEntity;
    fl::Material *lit = nullptr;
    fl::Material *unlit = nullptr;
    fl::IndirectLight *ibl = nullptr;
    fl::Texture *envCubemap = nullptr;
    fl::Skybox *skybox = nullptr;
    fl::ColorGrading *colorGrading = nullptr;
    Sky skyModel;   // shared gradient (also drives the Cycles world) — see Sky.h
    // Material texture maps → GPU textures, cached by source-Image identity
    // (ImgBase*) so a reused map uploads once and static meshes don't re-create
    // a texture every sync. whiteTex is the 1x1 default bound to unused samplers.
    std::unordered_map<const void *, fl::Texture *> textureCache;
    fl::Texture *whiteTex = nullptr;
    flm::float3 skyUp{0, 1, 0};

    utils::Size targetSize{640, 480};
    utils::Size swapSize{0, 0};
    std::vector<uint8_t> colorRGBA;   // last frame, W*H*4, row 0 = top
    utils::Size colorSize{0, 0};

    std::unordered_map<Node *, NodeCache> cache;
    std::vector<::utils::Entity> lightEntities;   // rebuilt every frame

    // Settings. First-class contract flags (set via the typed seam methods) +
    // Configurable knob values (set from the render.* properties, applied on the
    // render thread via the dirty flags so Filament calls stay single-threaded).
    float ambient = 0.2f, exposure = 1.0f, overlayAlpha = 1.0f;
    bool ssr = true, shadows = true, lighting = true, showSky = false;
    bool taa = false;   // temporal AA — resolves SSR's per-pixel dither; off for
                        // single-shot/headless (needs frame history) → FXAA instead.
    int debugMode = 0;
    float lightScale = 1.0f, envIntensity = 0.95f, envSpecular = 1.0f, ssrThickness = 1.0f, ssrMaxDist = 200.0f;
    // Screen-space ambient occlusion — the soft contact darkening under/between
    // objects (the sphere occluding the sky dome from the ground). This is the
    // Filament analogue of the ambient-occlusion contact shadow Cycles gets for
    // free by path-tracing the environment; a light shadow-map can't produce it.
    // NB Filament's AO radius is in world units ("metres"); viz3d scenes are 100s
    // of units, so the 0.3 default is invisible — we default to a scene-scale value.
    // DEFAULT OFF. Screen-space AO on a large grazing flat ground can't be both
    // clean and effective: bias=0 gives eye-hurting self-occlusion acne on the
    // floor, and a bias high enough to clean it also cancels the contact darkening —
    // and it never matches Cycles' path-traced contact AO anyway. So it's an opt-in
    // knob (still useful for concave object-to-object contact, not flat floors);
    // raise `ambient occlusion` + `ao radius` to enable. Defaults below apply then.
    bool ssao = false; float aoRadius = 100.0f, aoIntensity = 1.5f, aoBias = 0.0f;
    int aoType = 0;   // 0 = SAO, 1 = GTAO (GTAO globally over-darkens grazing planes)
    float aoMinHorizon = 0.2f;
    int toneMap = 0;   // 0 linear, 1 filmic, 2 aces, 3 pbr-neutral
    std::atomic<bool> envDirty{false}, gradingDirty{false}, aaDirty{true};

    // Antialiasing mode. Filament's SSR is a per-pixel-dithered temporal effect
    // that only resolves under TAA; without it the dither shows as a fixed
    // diagonal cross-hatch on every reflective (i.e. every) surface. So: SSR-on
    // paths enable TAA to denoise it; single-shot/headless (no frame history)
    // keep it off and use cheap FXAA for edges. Called only on the render thread.
    void applyAA() {
      view->setAntiAliasing(taa ? fl::View::AntiAliasing::NONE
                                : fl::View::AntiAliasing::FXAA);
      fl::View::TemporalAntiAliasingOptions t;
      t.enabled = taa;
      // Dynamically damp the history feedback to kill the occasional bright
      // temporal firefly/flash (a sharp SSR/specular reflection of the bright sky
      // getting amplified across frames).
      t.preventFlickering = true;
      view->setTemporalAntiAliasingOptions(t);
    }

    void rebuildColorGrading() {
      if (colorGrading) { view->setColorGrading(nullptr); engine->destroy(colorGrading); colorGrading = nullptr; }
      auto build = [&](const fl::ToneMapper &tm) {
        return fl::ColorGrading::Builder().toneMapper(&tm).build(*engine);
      };
      switch (toneMap) {
        case 1: { fl::FilmicToneMapper tm;      colorGrading = build(tm); break; }
        case 2: { fl::ACESToneMapper tm;        colorGrading = build(tm); break; }
        case 3: { fl::PBRNeutralToneMapper tm;  colorGrading = build(tm); break; }
        default: { fl::LinearToneMapper tm;     colorGrading = build(tm); break; }
      }
      view->setColorGrading(colorGrading);
    }

    void ensureSwapChain() {
      if (swapChain && swapSize == targetSize) return;
      if (swapChain) { engine->destroy(swapChain); swapChain = nullptr; }
      swapChain = engine->createSwapChain(targetSize.width, targetSize.height,
                                          fl::SwapChain::CONFIG_READABLE);
      swapSize = targetSize;
      view->setViewport({0, 0, (uint32_t)targetSize.width,
                         (uint32_t)targetSize.height});
    }

    void destroyPrim(Prim &p) {
      if (p.inScene) { fscene->remove(p.entity); p.inScene = false; }
      if (p.entity) {
        auto &rm = engine->getRenderableManager();
        if (rm.hasComponent(p.entity)) rm.destroy(p.entity);
        auto &tm = engine->getTransformManager();
        if (tm.hasComponent(p.entity)) tm.destroy(p.entity);
        ::utils::EntityManager::get().destroy(p.entity);
        p.entity = {};
      }
      if (p.mi) { engine->destroy(p.mi); p.mi = nullptr; }
      if (p.vb) { engine->destroy(p.vb); p.vb = nullptr; }
      if (p.ib) { engine->destroy(p.ib); p.ib = nullptr; }
    }

    void destroyCache(NodeCache &nc) {
      destroyPrim(nc.solid);
      for (auto &p : nc.lineGroups) destroyPrim(p);
      nc.lineGroups.clear();
    }

    void clearCache() {
      for (auto &kv : cache) destroyCache(kv.second);
      cache.clear();
    }

    void clearTextures() {
      for (auto &kv : textureCache) engine->destroy(kv.second);
      textureCache.clear();
      if (whiteTex) { engine->destroy(whiteTex); whiteTex = nullptr; }
    }

    // 1x1 opaque-white default, bound to any sampler whose map is absent so the
    // shader's texture multiplies become no-ops.
    fl::Texture *white() {
      if (whiteTex) return whiteTex;
      auto *data = new uint8_t[4]{255, 255, 255, 255};
      whiteTex = fl::Texture::Builder().width(1).height(1).levels(1)
          .sampler(fl::Texture::Sampler::SAMPLER_2D)
          .format(fl::Texture::InternalFormat::RGBA8).build(*engine);
      whiteTex->setImage(*engine, 0, fl::Texture::PixelBufferDescriptor(
          data, 4, fl::backend::PixelDataFormat::RGBA,
          fl::backend::PixelDataType::UBYTE,
          [](void *p, size_t, void *) { delete[] static_cast<uint8_t *>(p); }));
      return whiteTex;
    }

    // Upload an ICL Image as an RGBA8 texture (sRGB internal format for colour
    // maps → Filament linearises on sample; plain RGBA8 for linear data maps).
    // Cached by ImgBase identity. Returns white() for a null/non-8u image.
    fl::Texture *texture(const core::Image &img, bool srgb) {
      if (img.isNull()) return white();
      const void *key = img.ptr();
      auto it = textureCache.find(key);
      if (it != textureCache.end()) return it->second;
      if (img.getDepth() != core::depth8u) return white();   // 8u maps only (for now)

      const int w = img.getWidth(), h = img.getHeight(), ch = img.getChannels();
      const auto &s = img.as<icl8u>();
      const icl8u *R = s.getData(0);
      const icl8u *G = ch > 1 ? s.getData(1) : R;
      const icl8u *B = ch > 2 ? s.getData(2) : R;
      const icl8u *A = ch > 3 ? s.getData(3) : nullptr;
      auto *data = new uint8_t[size_t(w) * h * 4];
      for (int i = 0; i < w * h; ++i) {
        data[i * 4 + 0] = R[i]; data[i * 4 + 1] = G[i];
        data[i * 4 + 2] = B[i]; data[i * 4 + 3] = A ? A[i] : 255;
      }
      auto *tex = fl::Texture::Builder().width(w).height(h).levels(1)
          .sampler(fl::Texture::Sampler::SAMPLER_2D)
          .format(srgb ? fl::Texture::InternalFormat::SRGB8_A8
                       : fl::Texture::InternalFormat::RGBA8).build(*engine);
      tex->setImage(*engine, 0, fl::Texture::PixelBufferDescriptor(
          data, size_t(w) * h * 4, fl::backend::PixelDataFormat::RGBA,
          fl::backend::PixelDataType::UBYTE,
          [](void *p, size_t, void *) { delete[] static_cast<uint8_t *>(p); }));
      textureCache[key] = tex;
      return tex;
    }

    // Set a renderable's world transform (Filament's model matrix for the node).
    void setPrimTransform(Prim &p, const flm::mat4 &m) {
      if (!p.entity) return;
      auto &tm = engine->getTransformManager();
      tm.setTransform(tm.getInstance(p.entity), m);
    }

    // --- Lighting: rebuilt each frame (lights are cheap; positions animate) ---
    void clearLights() {
      auto &lm = engine->getLightManager();
      for (auto e : lightEntities) {
        fscene->remove(e);
        if (lm.hasComponent(e)) lm.destroy(e);
        ::utils::EntityManager::get().destroy(e);
      }
      lightEntities.clear();
    }

    // Directional light: intensity is illuminance in lux (flat, no falloff).
    // kDirLux carries the historical directional-key-light brightness so explicit
    // directional lights and the no-lights fallback look unchanged after the switch
    // to physical point lights; `lightScale` is the unitless user brightness knob.
    static constexpr float kDirLux = 3.0f;

    void addDirectional(flm::float3 dir, flm::float3 color, float lux, bool shadow) {
      auto e = ::utils::EntityManager::get().create();
      fl::LightManager::Builder(fl::LightManager::Type::DIRECTIONAL)
          .color({color[0], color[1], color[2]})
          .intensity(lux)
          .direction(normalized(dir))
          .castShadows(shadow && shadows)
          .build(*engine, e);
      fscene->addEntity(e);
      lightEntities.push_back(e);
    }

    // Physical point light with inverse-square falloff, unit-matched to the Cycles
    // PointLight (see SceneSynchronizer::syncLights): Cycles sets a radiant
    // "strength" = inten·(300/255)·d0² (d0=500) and its irradiance falls off as
    // strength/(4π r²). A Filament point light with luminous intensity `candela`
    // produces illuminance candela/r², so the candela reproducing that same
    // irradiance is kPointCalib·strength/(4π) — kPointCalib is the one photometric
    // constant that ties Filament's lumens to Cycles' watts (calibrated on the
    // diffuse rung of viz3d-render-calibrate). Because both sides now share the
    // exact inverse-square model, this single constant holds at every distance.
    static constexpr float kPointCalib = 1.35f;

    void addPoint(flm::float3 pos, flm::float3 color, float candela, bool shadow) {
      auto e = ::utils::EntityManager::get().create();
      fl::LightManager::Builder(fl::LightManager::Type::POINT)
          .color({color[0], color[1], color[2]})
          .intensityCandela(candela)
          .position(pos)
          .falloff(5000.0f)   // sphere of influence — large vs the scene, ~pure inverse-square
          .castShadows(shadow && shadows)
          .build(*engine, e);
      fscene->addEntity(e);
      lightEntities.push_back(e);
    }

    void collectLights(Node *node) {
      if (!node || !node->isVisible()) return;
      if (auto *light = dynamic_cast<LightNode *>(node)) {
        Mat t = light->getTransformation(true);
        GeomColor c = light->getColor();
        if (c[0] > 1.01f || c[1] > 1.01f || c[2] > 1.01f) c = c * (1.0f / 255.0f);
        const float inten = light->getIntensity();
        flm::float3 pos{t(0, 3), t(1, 3), t(2, 3)};
        if (light->getLightType() == LightNode::Directional) {
          // Directional transform's translation encodes the direction.
          addDirectional(pos, toLinear(c), kDirLux * lightScale * inten,
                         light->getShadowEnabled());
        } else {
          // Point (and Spot, approximated as point for now): real inverse-square.
          constexpr float d0 = 500.0f;
          const float strength = inten * (300.0f / 255.0f) * d0 * d0;
          const float candela = kPointCalib * lightScale * strength / (4.0f * float(M_PI));
          addPoint(pos, toLinear(c), candela, light->getShadowEnabled());
        }
      }
      if (auto *g = dynamic_cast<GroupNode *>(node))
        for (int i = 0; i < g->getChildCount(); ++i) collectLights(g->getChild(i));
    }

    // Procedural sky-gradient environment: a small HDR cubemap for specular
    // reflections (box-mipped as an approximate roughness prefilter) + its
    // radiance SH for diffuse ambient. Replaces a flat grey ambient so
    // reflective/metallic surfaces reflect a coloured, directional environment.
    void buildEnvironment() {
      if (skybox) { fscene->setSkybox(nullptr); engine->destroy(skybox); skybox = nullptr; }
      if (ibl) { fscene->setIndirectLight(nullptr); engine->destroy(ibl); ibl = nullptr; }
      if (envCubemap) { engine->destroy(envCubemap); envCubemap = nullptr; }

      const int N = 64;
      // Evaluate the shared Sky gradient (same model the Cycles world uses).
      auto sky = [&](const flm::float3 &d) -> flm::float3 {
        float t = d[0] * skyUp[0] + d[1] * skyUp[1] + d[2] * skyUp[2];   // -1..1
        cv3d::GeomColor c = skyModel.colorForElevation(t);
        return {c[0], c[1], c[2]};
      };
      auto faceDir = [](int f, float u, float v) -> flm::float3 {
        switch (f) {
          case 0: return {1, -v, -u};  case 1: return {-1, -v, u};
          case 2: return {u, 1, v};    case 3: return {u, -1, -v};
          case 4: return {u, -v, 1};   default: return {-u, -v, -1};
        }
      };

      // Level 0: the full-res sky + accumulate the diffuse radiance SH.
      std::vector<float> cur(size_t(6) * N * N * 4);   // RGBA per texel, 6 faces
      double sh[9][3] = {{0}};
      for (int f = 0; f < 6; ++f)
        for (int y = 0; y < N; ++y)
          for (int x = 0; x < N; ++x) {
            float u = 2.0f * (x + 0.5f) / N - 1.0f, v = 2.0f * (y + 0.5f) / N - 1.0f;
            flm::float3 d = normalized(faceDir(f, u, v));
            flm::float3 c = sky(d);
            float *px = &cur[((size_t(f) * N + y) * N + x) * 4];
            px[0] = c[0]; px[1] = c[1]; px[2] = c[2]; px[3] = 1.0f;
            float dOmega = (2.0f / N) * (2.0f / N) / std::pow(u * u + v * v + 1.0f, 1.5f);
            const double Y[9] = {0.282095, 0.488603 * d[1], 0.488603 * d[2], 0.488603 * d[0],
                                 1.092548 * d[0] * d[1], 1.092548 * d[1] * d[2],
                                 0.315392 * (3 * d[2] * d[2] - 1), 1.092548 * d[0] * d[2],
                                 0.546274 * (d[0] * d[0] - d[1] * d[1])};
            for (int i = 0; i < 9; ++i)
              for (int k = 0; k < 3; ++k) sh[i][k] += double(c[k]) * Y[i] * dOmega;
          }

      // Full mip chain, box-downsampled on the CPU (GPU generateMipmaps panics on
      // cubemaps here). reflections() samples a higher mip for rougher surfaces →
      // rough = blurry. Not a GGX prefilter, but a good approximation for a smooth
      // sky; upgrade to Filament's iblprefilter if a detailed HDR env is used.
      int mips = 1; while ((N >> mips) > 0) ++mips;
      envCubemap = fl::Texture::Builder().width(N).height(N).levels((uint8_t)mips)
          .sampler(fl::Texture::Sampler::SAMPLER_CUBEMAP)
          .format(fl::Texture::InternalFormat::RGBA16F).build(*engine);
      auto freeF = [](void *p, size_t, void *) { delete[] static_cast<float *>(p); };
      auto upload = [&](int level, int sz, const std::vector<float> &data) {
        auto *h = new float[data.size()];
        std::copy(data.begin(), data.end(), h);
        envCubemap->setImage(*engine, level, 0, 0, 0, (uint32_t)sz, (uint32_t)sz, 6,
            fl::Texture::PixelBufferDescriptor(h, data.size() * sizeof(float),
                fl::backend::PixelDataFormat::RGBA, fl::backend::PixelDataType::FLOAT, freeF));
      };
      upload(0, N, cur);
      for (int level = 1, sz = N; level < mips; ++level) {
        const int nsz = sz / 2;
        std::vector<float> next(size_t(6) * nsz * nsz * 4);
        for (int f = 0; f < 6; ++f)
          for (int y = 0; y < nsz; ++y)
            for (int x = 0; x < nsz; ++x)
              for (int c = 0; c < 4; ++c) {
                auto at = [&](int xx, int yy) { return cur[((size_t(f) * sz + yy) * sz + xx) * 4 + c]; };
                next[((size_t(f) * nsz + y) * nsz + x) * 4 + c] =
                    0.25f * (at(2 * x, 2 * y) + at(2 * x + 1, 2 * y) +
                             at(2 * x, 2 * y + 1) + at(2 * x + 1, 2 * y + 1));
              }
        upload(level, nsz, next);
        cur = std::move(next);
        sz = nsz;
      }

      // Decouple specular from diffuse: Filament's single IBL intensity scales
      // BOTH the environment reflection AND the diffuse SH ambient. We control
      // them independently — `envSpecular` scales the reflection (how strongly
      // surfaces mirror the sky; too high washes matte/grazing surfaces toward the
      // bright sky), `envIntensity` the diffuse ambient fill. The drawn skybox is
      // a separate object and stays full-bright either way.
      //   intensity = envSpecular  → reflections = envSpecular * cubemap
      //   SH pre-scaled by envIntensity/envSpecular → diffuse = envIntensity * sh
      const float spec = std::max(1e-3f, envSpecular);
      flm::float3 shf[9];
      for (int i = 0; i < 9; ++i)
        shf[i] = {(float)sh[i][0] * envIntensity / spec, (float)sh[i][1] * envIntensity / spec,
                  (float)sh[i][2] * envIntensity / spec};
      // Filament's SH irradiance is evaluated in a frame whose Y is mirrored vs
      // ours (the same Y-handedness flip the geometry path compensates via the
      // projection/winding — see P2). The cubemap sampling path (skybox +
      // reflections) is NOT affected, so this correction is local to the SH: mirror
      // the environment in Y by negating the y-odd bands (l=1 m=-1, l=2 m=-2/-1).
      // Without it a matte sphere's diffuse gradient renders upside-down (zenith
      // light on its underside). The DC term (average) is untouched.
      shf[1] = -shf[1]; shf[4] = -shf[4]; shf[5] = -shf[5];
      ibl = fl::IndirectLight::Builder().reflections(envCubemap).radiance(3, shf)
          .intensity(spec).build(*engine);
      fscene->setIndirectLight(ibl);

      // Draw the same gradient as the background (skybox) so the realtime preview
      // shows the sky like the Cycles world, not a flat clear colour. Shares the
      // env cubemap (Skybox holds a reference; we free the texture once, last).
      skybox = fl::Skybox::Builder().environment(envCubemap).showSun(false).build(*engine);
      fscene->setSkybox(showSky ? skybox : nullptr);
    }

    void syncLights(const std::vector<std::shared_ptr<Node>> &nodes) {
      clearLights();
      if (!lighting) return;
      size_t before = lightEntities.size();
      for (const auto &n : nodes) collectLights(n.get());
      if (lightEntities.size() == before)   // no scene lights → default key light
        addDirectional({-0.4f, -1.0f, -0.6f}, {1.0f, 0.98f, 0.95f},
                       kDirLux * lightScale, false);
    }

    // Expand triangles + quads into a non-indexed position+normal list, honouring
    // the node's smooth/flat shading (mirrors the GL backend's GeomCache).
    void expand(const GeometryNode *geom, std::vector<flm::float3> &P,
                std::vector<flm::float3> &N, std::vector<flm::float2> &UV) {
      const auto &verts = geom->getVertices();
      const auto &norms = geom->getNormals();
      const auto &texc = geom->getTexCoords();
      const bool smooth = geom->getSmoothShading();
      auto uvOf = [&](int ti) {
        if (ti >= 0 && ti < (int)texc.size()) return flm::float2{texc[ti].x, texc[ti].y};
        return flm::float2{0.0f, 0.0f};
      };
      auto emitTri = [&](int a, int b, int c, int na, int nb, int nc,
                         int ta, int tb, int tc) {
        flm::float3 pa{verts[a][0], verts[a][1], verts[a][2]};
        flm::float3 pb{verts[b][0], verts[b][1], verts[b][2]};
        flm::float3 pc{verts[c][0], verts[c][1], verts[c][2]};
        flm::float3 fn = normalized(cross(pb - pa, pc - pa));
        auto nrm = [&](int ni) {
          if (smooth && ni >= 0 && ni < (int)norms.size())
            return flm::float3{norms[ni][0], norms[ni][1], norms[ni][2]};
          return fn;
        };
        P.push_back(pa); N.push_back(nrm(na)); UV.push_back(uvOf(ta));
        P.push_back(pb); N.push_back(nrm(nb)); UV.push_back(uvOf(tb));
        P.push_back(pc); N.push_back(nrm(nc)); UV.push_back(uvOf(tc));
      };
      if (geom->isPrimitiveVisible(PrimTriangle))
        for (const auto &t : geom->getTriangles())
          emitTri(t.v[0], t.v[1], t.v[2], t.n[0], t.n[1], t.n[2], t.t[0], t.t[1], t.t[2]);
      if (geom->isPrimitiveVisible(PrimQuad))
        for (const auto &q : geom->getQuads()) {
          emitTri(q.v[0], q.v[1], q.v[2], q.n[0], q.n[1], q.n[2], q.t[0], q.t[1], q.t[2]);
          emitTri(q.v[0], q.v[2], q.v[3], q.n[0], q.n[2], q.n[3], q.t[0], q.t[2], q.t[3]);
        }
    }

    // Instantiate a Prim renderable from finished buffers + material + topology.
    void buildPrim(Prim &p, fl::VertexBuffer *vb, fl::IndexBuffer *ib, size_t count,
                   fl::MaterialInstance *mi, fl::RenderableManager::PrimitiveType topo,
                   const flm::float3 &lo, const flm::float3 &hi, bool shadows) {
      p.vb = vb; p.ib = ib; p.mi = mi;
      p.entity = ::utils::EntityManager::get().create();
      fl::RenderableManager::Builder(1)
          .boundingBox({{(lo[0] + hi[0]) * 0.5f, (lo[1] + hi[1]) * 0.5f, (lo[2] + hi[2]) * 0.5f},
                        {(hi[0] - lo[0]) * 0.5f + 1, (hi[1] - lo[1]) * 0.5f + 1, (hi[2] - lo[2]) * 0.5f + 1}})
          .material(0, mi)
          .geometry(0, topo, vb, ib, 0, count)
          .castShadows(shadows).receiveShadows(shadows)
          .culling(false)
          .build(*engine, p.entity);
      engine->getTransformManager().create(p.entity);
      fscene->addEntity(p.entity);
      p.inScene = true;
    }

    // Solid mesh (triangles + quads) → lit PBR renderable.
    void buildSolid(GeometryNode *geom, Prim &p) {
      std::vector<flm::float3> P, N;
      std::vector<flm::float2> UV;
      expand(geom, P, N, UV);
      const size_t nv = P.size();
      if (nv < 3) return;

      // Tangent frames (quaternions) — Filament derives the shading normal from
      // these for lit materials. normals-only is fine without normal maps.
      auto *so = fgeo::SurfaceOrientation::Builder()
                     .vertexCount((uint32_t)nv).normals(N.data()).build();
      auto *quatBuf = new flm::quatf[nv];
      so->getQuats(quatBuf, nv);
      delete so;

      // Heap copies handed to Filament (consumed asynchronously at flushAndWait,
      // after this function returns → pointers into locals would dangle).
      auto *posBuf = new flm::float3[nv];
      flm::float3 lo{1e30f, 1e30f, 1e30f}, hi{-1e30f, -1e30f, -1e30f};
      for (size_t i = 0; i < nv; ++i) {
        posBuf[i] = P[i];
        for (int k = 0; k < 3; ++k) { lo[k] = std::min(lo[k], P[i][k]); hi[k] = std::max(hi[k], P[i][k]); }
      }
      auto *uvBuf = new flm::float2[nv];
      for (size_t i = 0; i < nv; ++i) uvBuf[i] = UV[i];
      auto *idxBuf = new uint32_t[nv];
      for (uint32_t i = 0; i < nv; ++i) idxBuf[i] = i;

      auto freeF3 = [](void *q, size_t, void *) { delete[] static_cast<flm::float3 *>(q); };
      auto freeF2 = [](void *q, size_t, void *) { delete[] static_cast<flm::float2 *>(q); };
      auto freeQ = [](void *q, size_t, void *) { delete[] static_cast<flm::quatf *>(q); };
      auto freeU32 = [](void *q, size_t, void *) { delete[] static_cast<uint32_t *>(q); };

      auto *vb = fl::VertexBuffer::Builder()
          .vertexCount((uint32_t)nv).bufferCount(3)
          .attribute(fl::VertexAttribute::POSITION, 0,
                     fl::VertexBuffer::AttributeType::FLOAT3, 0, sizeof(flm::float3))
          .attribute(fl::VertexAttribute::TANGENTS, 1,
                     fl::VertexBuffer::AttributeType::FLOAT4, 0, sizeof(flm::quatf))
          .attribute(fl::VertexAttribute::UV0, 2,
                     fl::VertexBuffer::AttributeType::FLOAT2, 0, sizeof(flm::float2))
          .build(*engine);
      vb->setBufferAt(*engine, 0, fl::VertexBuffer::BufferDescriptor(posBuf, nv * sizeof(flm::float3), freeF3));
      vb->setBufferAt(*engine, 1, fl::VertexBuffer::BufferDescriptor(quatBuf, nv * sizeof(flm::quatf), freeQ));
      vb->setBufferAt(*engine, 2, fl::VertexBuffer::BufferDescriptor(uvBuf, nv * sizeof(flm::float2), freeF2));
      auto *ib = fl::IndexBuffer::Builder().indexCount((uint32_t)nv)
          .bufferType(fl::IndexBuffer::IndexType::UINT).build(*engine);
      ib->setBuffer(*engine, fl::IndexBuffer::BufferDescriptor(idxBuf, nv * sizeof(uint32_t), freeU32));

      buildPrim(p, vb, ib, nv, lit->createInstance(),
                fl::RenderableManager::PrimitiveType::TRIANGLES, lo, hi, true);
      updateSolidMaterial(geom, p);
    }

    // One LINES renderable for a set of same-colour segments (unlit, flat colour).
    void buildLineGroup(GeometryNode *geom, const std::vector<int> &endpoints,
                        const GeomColor &color, std::vector<Prim> &out) {
      const auto &verts = geom->getVertices();
      const size_t nv = endpoints.size();
      auto *posBuf = new flm::float3[nv];
      flm::float3 lo{1e30f, 1e30f, 1e30f}, hi{-1e30f, -1e30f, -1e30f};
      for (size_t i = 0; i < nv; ++i) {
        int vi = endpoints[i];
        posBuf[i] = {verts[vi][0], verts[vi][1], verts[vi][2]};
        for (int c = 0; c < 3; ++c) { lo[c] = std::min(lo[c], posBuf[i][c]); hi[c] = std::max(hi[c], posBuf[i][c]); }
      }
      auto *idxBuf = new uint32_t[nv];
      for (uint32_t i = 0; i < nv; ++i) idxBuf[i] = i;
      auto freeF3 = [](void *q, size_t, void *) { delete[] static_cast<flm::float3 *>(q); };
      auto freeU32 = [](void *q, size_t, void *) { delete[] static_cast<uint32_t *>(q); };

      auto *vb = fl::VertexBuffer::Builder().vertexCount((uint32_t)nv).bufferCount(1)
          .attribute(fl::VertexAttribute::POSITION, 0, fl::VertexBuffer::AttributeType::FLOAT3,
                     0, sizeof(flm::float3))
          .build(*engine);
      vb->setBufferAt(*engine, 0, fl::VertexBuffer::BufferDescriptor(posBuf, nv * sizeof(flm::float3), freeF3));
      auto *ib = fl::IndexBuffer::Builder().indexCount((uint32_t)nv)
          .bufferType(fl::IndexBuffer::IndexType::UINT).build(*engine);
      ib->setBuffer(*engine, fl::IndexBuffer::BufferDescriptor(idxBuf, nv * sizeof(uint32_t), freeU32));

      auto *mi = unlit->createInstance();
      mi->setParameter("color", toLinear(color));
      out.emplace_back();
      buildPrim(out.back(), vb, ib, nv, mi,
                fl::RenderableManager::PrimitiveType::LINES, lo, hi, false);
    }

    // Wireframe lines → unlit 1px LINES, one renderable per distinct colour.
    // Grouping by colour keeps each line batch on a flat-colour unlit material
    // (typical line sets have few colours — 3 for a coordinate frame); per-vertex
    // colour is deferred to the point-cloud path, where it's unavoidable. Thick
    // lines (setLineWidth) would need screen-space quad expansion — a follow-up.
    void buildLines(GeometryNode *geom, std::vector<Prim> &out) {
      if (!geom->isPrimitiveVisible(PrimLine)) return;
      const auto &lines = geom->getLines();
      if (lines.empty()) return;
      auto mat = geom->getMaterial();
      GeomColor defc(1, 1, 1, 1);
      if (mat) defc = (mat->lineColor[3] > 0) ? mat->lineColor : mat->baseColor;

      auto key = [](const GeomColor &c) {
        auto q = [](float v) { return (uint32_t)std::clamp(int(v * 255.f + 0.5f), 0, 255); };
        return q(c[0]) | (q(c[1]) << 8) | (q(c[2]) << 16) | (q(c[3]) << 24);
      };
      std::unordered_map<uint32_t, std::vector<int>> byColor;   // colourKey → endpoints
      std::unordered_map<uint32_t, GeomColor> colorOf;
      for (const auto &l : lines) {
        GeomColor c = (l.color[3] > 0.001f) ? l.color : defc;
        uint32_t k = key(c);
        colorOf[k] = c;
        auto &e = byColor[k];
        e.push_back(l.a); e.push_back(l.b);
      }
      for (auto &kv : byColor) buildLineGroup(geom, kv.second, colorOf[kv.first], out);
    }

    void syncGeometry(GeometryNode *geom) {
      NodeCache &nc = cache[geom];
      const uint64_t v = geom->getGeometryVersion();
      if (nc.builtVersion != v) {   // (re)build geometry
        destroyCache(nc);
        buildSolid(geom, nc.solid);
        buildLines(geom, nc.lineGroups);
        nc.builtVersion = v;
      } else {
        updateSolidMaterial(geom, nc.solid);   // colours may change without a rebuild
      }
      // Transform can change every frame independently of geometry version.
      flm::mat4 m = toFilament(geom->getTransformation(true));
      setPrimTransform(nc.solid, m);
      for (auto &p : nc.lineGroups) setPrimTransform(p, m);
    }

    void updateSolidMaterial(GeometryNode *geom, Prim &p) {
      if (!p.mi) return;
      auto mat = geom->getMaterial();
      cv3d::GeomColor bc = mat ? mat->baseColor : cv3d::GeomColor{0.78f, 0.78f, 0.78f, 1.0f};
      float metallic = mat ? mat->metallic : 0.0f;
      float roughness = mat ? mat->roughness : 0.6f;
      cv3d::GeomColor em = mat ? mat->emissive : cv3d::GeomColor{0, 0, 0, 1};

      // Straight 1:1 glTF metallic-roughness → Filament. A mirror is metallic=1,
      // roughness≈0 (authored in the material); no special "reflectivity" remap.
      p.mi->setParameter("baseColor", toLinear(bc));
      p.mi->setParameter("metallic", metallic);
      p.mi->setParameter("roughness", std::max(0.045f, roughness));
      p.mi->setParameter("reflectance", 0.5f);   // base dielectric F0 (4%)
      p.mi->setParameter("emissive", toLinear(em));
      // "enable lighting" off → flat unlit base colour (ICL contract).
      p.mi->setParameter("unlit", lighting ? 0.0f : 1.0f);

      // Texture maps (glTF metallic-roughness). Absent maps fall back to the 1x1
      // white default so the shader multiplies are no-ops. Colour maps are sRGB;
      // the metallic-roughness map is linear data.
      const Material::TextureMaps *tx = mat && mat->textures ? mat->textures.get() : nullptr;
      const bool nn = tx && tx->filter == Material::TexFilter::Nearest;
      fl::TextureSampler smp(
          nn ? fl::TextureSampler::MagFilter::NEAREST : fl::TextureSampler::MagFilter::LINEAR,
          fl::TextureSampler::WrapMode::REPEAT);
      p.mi->setParameter("baseColorMap",
          tx ? texture(tx->baseColorMap, true) : white(), smp);
      p.mi->setParameter("metallicRoughnessMap",
          tx ? texture(tx->metallicRoughnessMap, false) : white(), smp);
      p.mi->setParameter("emissiveMap",
          tx ? texture(tx->emissiveMap, true) : white(), smp);
    }

    void syncNode(Node *node) {
      if (!node || !node->isVisible()) return;
      if (dynamic_cast<LightNode *>(node)) return;   // lights handled in syncLights
      // Text is a textured billboard; the plan renders world labels in the 2D
      // overlay layer (not a Filament job). Until that lands, skip TextNodes so
      // they don't show as blank untextured quads. TODO: 2D label projection.
      if (dynamic_cast<TextNode *>(node)) return;
      if (auto *g = dynamic_cast<GroupNode *>(node)) {
        for (int i = 0; i < g->getChildCount(); ++i) syncNode(g->getChild(i));
        return;
      }
      if (auto *geom = dynamic_cast<GeometryNode *>(node)) syncGeometry(geom);
    }
  };

  FilamentRenderBackend::FilamentRenderBackend() : m_data(std::make_unique<Data>()) {
    m_data->engine = fl::Engine::create(fl::Engine::Backend::METAL);
    if (!m_data->engine) return;   // isValid() == false
    m_data->renderer = m_data->engine->createRenderer();
    m_data->view = m_data->engine->createView();
    m_data->fscene = m_data->engine->createScene();
    m_data->camEntity = ::utils::EntityManager::get().create();
    m_data->fcam = m_data->engine->createCamera(m_data->camEntity);
    m_data->view->setScene(m_data->fscene);
    m_data->view->setCamera(m_data->fcam);
    // Dithering defaults to TEMPORAL, which only resolves under TAA (we have none)
    // → it shows as a static diagonal cross-hatch on every surface. Turn it off and
    // use cheap FXAA to smooth edges instead.
    m_data->view->setDithering(fl::View::Dithering::NONE);
    m_data->applyAA();   // FXAA by default (taa=false); TAA when enabled
    m_data->rebuildColorGrading();   // tone mapping (default filmic)
    m_data->lit = fl::Material::Builder()
        .package(LIT_PBR_FILAMAT, sizeof(LIT_PBR_FILAMAT)).build(*m_data->engine);
    m_data->unlit = fl::Material::Builder()
        .package(UNLIT_SOLID_FILAMAT, sizeof(UNLIT_SOLID_FILAMAT)).build(*m_data->engine);

    // Procedural sky environment (reflections cubemap + diffuse SH).
    m_data->buildEnvironment();

    // --- Configurable knobs (surface in the OSD as render.* via Scene) ---
    // First-class features (lighting/SSR-on/off/debug) stay Scene properties routed
    // through the typed seam; these are Filament's own tunables. Changes are applied
    // on the render thread (dirty flags) so Filament calls stay single-threaded.
    // Range must be float (only Range<int>/Range<float> constraint adapters are
    // enrolled) — double literals would deduce Range<double> and throw at register.
    addProperty("exposure", utils::prop::Range{.min = 0.1f, .max = 3.0f, .step = 0.05f}, 1.0f);
    addProperty("light intensity", utils::prop::Range{.min = 0.0f, .max = 8.0f, .step = 0.1f}, 1.0f);
    addProperty("env intensity", utils::prop::Range{.min = 0.0f, .max = 1.5f, .step = 0.02f}, 0.95f);
    addProperty("env specular", utils::prop::Range{.min = 0.0f, .max = 1.0f, .step = 0.02f}, 1.0f);
    addProperty("tone mapping", utils::prop::Menu{"linear", "filmic", "aces", "pbr-neutral"}, "linear");
    addProperty("ssr thickness", utils::prop::Range{.min = 0.01f, .max = 10.0f, .step = 0.1f}, 1.0f);
    addProperty("ssr max distance", utils::prop::Range{.min = 1.0f, .max = 2000.0f, .step = 10.0f}, 200.0f);
    addProperty("ambient occlusion", utils::prop::Range{.min = 0.0f, .max = 1.0f, .step = 1.0f}, 0.0f);
    addProperty("ao radius", utils::prop::Range{.min = 0.0f, .max = 300.0f, .step = 5.0f}, 100.0f);
    addProperty("ao intensity", utils::prop::Range{.min = 0.0f, .max = 4.0f, .step = 0.1f}, 1.5f);
    addProperty("ao bias", utils::prop::Range{.min = 0.0f, .max = 2.0f, .step = 0.01f}, 0.0f);
    addProperty("ao type", utils::prop::Range{.min = 0.0f, .max = 1.0f, .step = 1.0f}, 0.0f);
    addProperty("ao minhorizon", utils::prop::Range{.min = 0.0f, .max = 0.7f, .step = 0.01f}, 0.2f);
    registerCallback([this](const utils::Configurable::Property &p) {
      Data &d = *m_data;
      auto num = [&] { try { return std::stof(p.as<std::string>()); } catch (...) { return 0.0f; } };
      if (p.name == "exposure") d.exposure = num();
      else if (p.name == "light intensity") d.lightScale = num();
      else if (p.name == "env intensity") { d.envIntensity = num(); d.envDirty = true; }
      else if (p.name == "env specular") { d.envSpecular = num(); d.envDirty = true; }
      else if (p.name == "ssr thickness") d.ssrThickness = num();
      else if (p.name == "ssr max distance") d.ssrMaxDist = num();
      else if (p.name == "ambient occlusion") d.ssao = num() > 0.5f;
      else if (p.name == "ao radius") d.aoRadius = num();
      else if (p.name == "ao intensity") d.aoIntensity = num();
      else if (p.name == "ao bias") d.aoBias = num();
      else if (p.name == "ao type") d.aoType = (int)num();
      else if (p.name == "ao minhorizon") d.aoMinHorizon = num();
      else if (p.name == "tone mapping") {
        std::string t = p.as<std::string>();
        d.toneMap = t == "filmic" ? 1 : t == "aces" ? 2 : t == "pbr-neutral" ? 3 : 0;
        d.gradingDirty = true;
      }
    });
  }

  FilamentRenderBackend::~FilamentRenderBackend() {
    if (!m_data->engine) return;
    m_data->clearCache();
    m_data->clearTextures();
    m_data->clearLights();
    fl::Engine *e = m_data->engine;
    if (m_data->colorGrading) e->destroy(m_data->colorGrading);
    if (m_data->skybox) e->destroy(m_data->skybox);
    if (m_data->ibl) e->destroy(m_data->ibl);
    if (m_data->envCubemap) e->destroy(m_data->envCubemap);
    if (m_data->lit) e->destroy(m_data->lit);
    if (m_data->unlit) e->destroy(m_data->unlit);
    if (m_data->fcam) e->destroyCameraComponent(m_data->camEntity);
    if (m_data->camEntity) ::utils::EntityManager::get().destroy(m_data->camEntity);
    if (m_data->view) e->destroy(m_data->view);
    if (m_data->fscene) e->destroy(m_data->fscene);
    if (m_data->renderer) e->destroy(m_data->renderer);
    if (m_data->swapChain) e->destroy(m_data->swapChain);
    fl::Engine::destroy(&e);
  }

  bool FilamentRenderBackend::isValid() const { return m_data->engine != nullptr; }

  void FilamentRenderBackend::setTargetSize(const utils::Size &size) {
    m_data->targetSize = size;
  }
  utils::Size FilamentRenderBackend::getTargetSize() const { return m_data->targetSize; }

  bool FilamentRenderBackend::readColor(core::Img8u &dst) const {
    if (!m_data->engine || m_data->colorRGBA.empty()) return false;
    const int W = m_data->colorSize.width, H = m_data->colorSize.height;
    dst.setChannels(3);
    dst.setSize(m_data->colorSize);
    core::Channel8u r = dst[0], g = dst[1], b = dst[2];
    const uint8_t *p = m_data->colorRGBA.data();
    for (int y = 0; y < H; ++y)
      for (int x = 0; x < W; ++x) {
        const uint8_t *px = p + (size_t(y) * W + x) * 4;  // row 0 = top
        r(x, y) = px[0]; g(x, y) = px[1]; b(x, y) = px[2];
      }
    return true;
  }

  void FilamentRenderBackend::render(const std::vector<std::shared_ptr<Node>> &nodes,
                                     const Mat &viewMatrix,
                                     const Mat &projectionMatrix) {
    if (!m_data->engine) return;
    m_data->ensureSwapChain();
    const int W = m_data->targetSize.width, H = m_data->targetSize.height;
    if (W <= 0 || H <= 0) return;

    // Apply Configurable changes on the render thread (Filament isn't thread-safe).
    if (m_data->gradingDirty.exchange(false)) m_data->rebuildColorGrading();
    if (m_data->envDirty.exchange(false)) m_data->buildEnvironment();
    if (m_data->aaDirty.exchange(false)) m_data->applyAA();

    // Inject ICL's calibrated projection + camera placement (the P2 recipe). The
    // near/far handed to Filament MUST match the ones baked into the matrix (they
    // drive Filament's depth-buffer range) — recover them from getProjectionMatrixGL's
    // A,B terms: near = B/(A-1), far = B/(A+1). A mismatch wrecks depth precision.
    const double A = projectionMatrix(2, 2), B = projectionMatrix(2, 3);
    double zn = B / (A - 1.0), zf = B / (A + 1.0);
    if (!(zn > 0.0) || !(zf > zn)) { zn = 1.0; zf = 100000.0; }   // guard degenerate
    m_data->fcam->setCustomProjection(toFilament(projectionMatrix), zn, zf);
    m_data->fcam->setModelMatrix(toFilament(viewMatrix.inv()));
    // Punctual (point/spot) lights are froxel-culled; the default cull range is
    // zLightFar=100m. viz3d scenes are 100s–1000s of world units from the camera,
    // so without this the froxelizer drops every point light. Spread the froxel
    // grid across the real camera depth range (directional lights are unaffected).
    m_data->view->setDynamicLightingOptions(std::max(0.01f, float(zn)), float(zf));
    // `exposure` is the global brightness (scales lit surfaces, sky AND
    // reflections uniformly) — lights are no longer scaled by it, so this is the
    // single scene-brightness knob. NB Filament's setExposure(e) maps to
    // ISO = 100/e, i.e. a LOWER e is BRIGHTER; we invert so the knob is intuitive
    // (higher = brighter). Default 1.25 ≈ +25% vs unity.
    m_data->fcam->setExposure(1.0f / std::max(1e-3f, m_data->exposure));

    // Screen-space reflections (first-class scene feature via setSSREnabled).
    // Distances are in world units — viz3d scenes are much larger than metres,
    // so scale the ray thickness/reach up from the metric defaults.
    fl::View::ScreenSpaceReflectionsOptions ssrOpt;
    ssrOpt.enabled = m_data->ssr;
    ssrOpt.thickness = m_data->ssrThickness;
    ssrOpt.maxDistance = m_data->ssrMaxDist;
    m_data->view->setScreenSpaceReflectionsOptions(ssrOpt);

    // Screen-space ambient occlusion (soft contact shadows from occluded ambient).
    // SAO at FULL resolution (half-res + upsample speckles a flat plane), and — the
    // real fix for the ground acne — a world-scale `bias`: SAO's self-occlusion bias
    // is in world units, and the 0.5mm default self-occludes our 100s-of-units
    // ground. GTAO instead globally darkens the whole grazing-angle plane, so SAO
    // with a proper bias is the better fit for these large-flat-ground scenes.
    fl::AmbientOcclusionOptions ao;
    ao.enabled = m_data->ssao && m_data->aoRadius > 0.0f;
    ao.aoType = m_data->aoType == 1 ? fl::AmbientOcclusionOptions::AmbientOcclusionType::GTAO
                                    : fl::AmbientOcclusionOptions::AmbientOcclusionType::SAO;
    ao.radius = m_data->aoRadius;
    ao.intensity = m_data->aoIntensity;
    ao.bias = m_data->aoBias;       // world units — high enough to kill flat-plane
                                    // self-occlusion acne, low enough to keep contact
    ao.minHorizonAngleRad = m_data->aoMinHorizon;   // reject near-tangent occluders
                                    // (the flat ground self-occluding at grazing view)
                                    // while keeping steep ones (an object on the ground)
    ao.resolution = 1.0f;
    ao.gtao.sampleSliceCount = 4;
    ao.gtao.sampleStepsPerSlice = 3;
    ao.quality = fl::QualityLevel::HIGH;
    ao.lowPassFilter = fl::QualityLevel::HIGH;
    ao.upsampling = fl::QualityLevel::HIGH;
    m_data->view->setAmbientOcclusionOptions(ao);

    m_data->syncLights(nodes);
    for (const auto &n : nodes) m_data->syncNode(n.get());

    m_data->colorRGBA.assign(size_t(W) * H * 4, 0);
    if (m_data->renderer->beginFrame(m_data->swapChain)) {
      m_data->renderer->render(m_data->view);
      m_data->renderer->readPixels(0, 0, W, H, fl::backend::PixelBufferDescriptor(
          m_data->colorRGBA.data(), m_data->colorRGBA.size(),
          fl::backend::PixelDataFormat::RGBA, fl::backend::PixelDataType::UBYTE));
      m_data->renderer->endFrame();
    }
    m_data->engine->flushAndWait();   // buffer descriptors consumed here
    m_data->colorSize = m_data->targetSize;
  }

  void FilamentRenderBackend::setExposure(float e) { m_data->exposure = e; }
  void FilamentRenderBackend::setAmbient(float a) { m_data->ambient = a; }
  void FilamentRenderBackend::setOverlayAlpha(float a) { m_data->overlayAlpha = a; }
  void FilamentRenderBackend::setSSREnabled(bool e) { m_data->ssr = e; }
  bool FilamentRenderBackend::isSSREnabled() const { return m_data->ssr; }
  void FilamentRenderBackend::setTemporalAAEnabled(bool e) {
    if (m_data->taa == e) return;   // no-op keeps TAA frame history intact
    m_data->taa = e;
    m_data->aaDirty = true;         // applied on the render thread
  }
  void FilamentRenderBackend::setShadowsEnabled(bool e) { m_data->shadows = e; }
  void FilamentRenderBackend::setLightingEnabled(bool e) { m_data->lighting = e; }
  void FilamentRenderBackend::setSkyEnabled(bool e) {
    if (m_data->showSky == e) return;
    m_data->showSky = e;
    m_data->envDirty = true;   // reattach/detach the drawn skybox on the render thread
  }
  void FilamentRenderBackend::setSkyUp(float x, float y, float z) {
    flm::float3 up = normalized({x, y, z});
    if (up[0] == m_data->skyUp[0] && up[1] == m_data->skyUp[1] && up[2] == m_data->skyUp[2])
      return;
    m_data->skyUp = up;
    if (m_data->engine) m_data->buildEnvironment();   // reorient the sky gradient
  }
  void FilamentRenderBackend::setDebugMode(int m) { m_data->debugMode = m; }
  void FilamentRenderBackend::invalidateCache() { if (m_data->engine) m_data->clearCache(); }
  void FilamentRenderBackend::flushInvalidatedCache() {}

} // namespace icl::viz3d
