// SPDX-License-Identifier: LGPL-3.0-or-later
// ICL - Image Component Library (https://github.com/iclcv/icl)
// Copyright (C) 2006-2026 Christof Elbrechter

#include <icl/viz3d/render/detail/FilamentRenderBackend.h>

#include <icl/viz3d/nodes/GroupNode.h>
#include <icl/viz3d/nodes/GeometryNode.h>
#include <icl/viz3d/nodes/LightNode.h>
#include <icl/viz3d/render/Material.h>

#include <filament/Camera.h>
#include <filament/Engine.h>
#include <filament/IndexBuffer.h>
#include <filament/IndirectLight.h>
#include <filament/LightManager.h>
#include <filament/Material.h>
#include <filament/MaterialInstance.h>
#include <filament/RenderableManager.h>
#include <filament/Renderer.h>
#include <filament/Scene.h>
#include <filament/SwapChain.h>
#include <filament/TransformManager.h>
#include <filament/VertexBuffer.h>
#include <filament/View.h>
#include <filament/Viewport.h>
#include <filament/Box.h>

#include <geometry/SurfaceOrientation.h>

#include <backend/PixelBufferDescriptor.h>
#include <math/mat4.h>
#include <math/quat.h>
#include <math/vec3.h>
#include <utils/EntityManager.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <unordered_map>
#include <vector>

// Compiled materials (matc -f header, generated by meson into builddir/icl/viz3d/).
// Referenced build-root-relative so they resolve via the always-present `-I.`
// (builddir root) without adding an include dir — adding ../icl/viz3d would shadow
// Cycles' `#include "scene/scene.h"` on the case-insensitive macOS FS
// (→ icl/viz3d/scene/Scene.h).
static const uint8_t LIT_PBR_FILAMAT[] = {
#include "icl/viz3d/lit_pbr.filamat.h"
};
static const uint8_t UNLIT_SOLID_FILAMAT[] = {
#include "icl/viz3d/unlit_solid.filamat.h"
};

namespace icl::viz3d {

  // NB: do NOT `using namespace filament` here — filament has math::/Scene/
  // Material/Camera that would collide with icl::math / icl::viz3d::Scene /
  // icl::viz3d::Material / icl::cv3d::Camera. Everything Filament is qualified.
  namespace fl = filament;
  namespace flm = filament::math;
  namespace fgeo = filament::geometry;

  namespace {
    // ICL row-major Mat -> Filament column-major mat4.
    flm::mat4 toFilament(const Mat &m) {
      flm::mat4 f;  // identity
      for (int c = 0; c < 4; ++c)
        for (int r = 0; r < 4; ++r)
          f[c][r] = m(r, c);
      return f;
    }

    flm::float3 normalized(flm::float3 v) {
      float l = std::sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
      return l > 1e-8f ? flm::float3{v[0] / l, v[1] / l, v[2] / l} : flm::float3{0, 0, 1};
    }

    // Per-node Filament geometry, keyed on the node's geometry version.
    struct NodeCache {
      fl::VertexBuffer *vb = nullptr;
      fl::IndexBuffer *ib = nullptr;
      fl::MaterialInstance *mi = nullptr;
      ::utils::Entity entity;    // renderable; also carries a transform component
      uint64_t builtVersion = ~0ull;
      bool inScene = false;
    };
  }

  struct FilamentRenderBackend::Data {
    fl::Engine *engine = nullptr;
    fl::SwapChain *swapChain = nullptr;
    fl::Renderer *renderer = nullptr;
    fl::View *view = nullptr;
    fl::Scene *fscene = nullptr;
    fl::Camera *fcam = nullptr;
    ::utils::Entity camEntity;
    fl::Material *lit = nullptr;
    fl::Material *unlit = nullptr;
    fl::IndirectLight *ibl = nullptr;

    utils::Size targetSize{640, 480};
    utils::Size swapSize{0, 0};
    std::vector<uint8_t> colorRGBA;   // last frame, W*H*4, row 0 = top
    utils::Size colorSize{0, 0};

    std::unordered_map<Node *, NodeCache> cache;
    std::vector<::utils::Entity> lightEntities;   // rebuilt every frame

    // Settings (stored; honoured incrementally through P3).
    float ambient = 0.2f, exposure = 1.0f, overlayAlpha = 1.0f;
    bool ssr = true, shadows = true, lighting = true, sky = false;
    int debugMode = 0;

    void ensureSwapChain() {
      if (swapChain && swapSize == targetSize) return;
      if (swapChain) { engine->destroy(swapChain); swapChain = nullptr; }
      swapChain = engine->createSwapChain(targetSize.width, targetSize.height,
                                          fl::SwapChain::CONFIG_READABLE);
      swapSize = targetSize;
      view->setViewport({0, 0, (uint32_t)targetSize.width,
                         (uint32_t)targetSize.height});
    }

    void destroyCache(NodeCache &nc) {
      if (nc.inScene) { fscene->remove(nc.entity); nc.inScene = false; }
      if (nc.entity) {
        auto &rm = engine->getRenderableManager();
        if (rm.hasComponent(nc.entity)) rm.destroy(nc.entity);
        auto &tm = engine->getTransformManager();
        if (tm.hasComponent(nc.entity)) tm.destroy(nc.entity);
        ::utils::EntityManager::get().destroy(nc.entity);
        nc.entity = {};
      }
      if (nc.mi) { engine->destroy(nc.mi); nc.mi = nullptr; }
      if (nc.vb) { engine->destroy(nc.vb); nc.vb = nullptr; }
      if (nc.ib) { engine->destroy(nc.ib); nc.ib = nullptr; }
    }

    void clearCache() {
      for (auto &kv : cache) destroyCache(kv.second);
      cache.clear();
    }

    // --- Lighting: rebuilt each frame (lights are cheap; positions animate) ---
    void clearLights() {
      auto &lm = engine->getLightManager();
      for (auto e : lightEntities) {
        fscene->remove(e);
        if (lm.hasComponent(e)) lm.destroy(e);
        ::utils::EntityManager::get().destroy(e);
      }
      lightEntities.clear();
    }

    void addDirectional(flm::float3 dir, flm::float3 color, float lux, bool shadow) {
      auto e = ::utils::EntityManager::get().create();
      fl::LightManager::Builder(fl::LightManager::Type::DIRECTIONAL)
          .color({color[0], color[1], color[2]})
          .intensity(lux)
          .direction(normalized(dir))
          .castShadows(shadow && shadows)
          .build(*engine, e);
      fscene->addEntity(e);
      lightEntities.push_back(e);
    }

    void collectLights(Node *node) {
      if (!node || !node->isVisible()) return;
      if (auto *light = dynamic_cast<LightNode *>(node)) {
        Mat t = light->getTransformation(true);
        GeomColor c = light->getColor();
        if (c[0] > 1.01f || c[1] > 1.01f || c[2] > 1.01f) c = c * (1.0f / 255.0f);
        const float inten = light->getIntensity();
        flm::float3 pos{t(0, 3), t(1, 3), t(2, 3)};
        // Approximate every light as directional (shining from its position toward
        // the origin) — sidesteps physical point-light falloff calibration in the
        // ambiguous viz3d unit scale. True point/spot lights are a P3 refinement.
        flm::float3 dir = normalized(flm::float3{-pos[0], -pos[1], -pos[2]});
        addDirectional(dir, {c[0], c[1], c[2]}, 80000.0f * inten * exposure,
                       light->getShadowEnabled());
      }
      if (auto *g = dynamic_cast<GroupNode *>(node))
        for (int i = 0; i < g->getChildCount(); ++i) collectLights(g->getChild(i));
    }

    void syncLights(const std::vector<std::shared_ptr<Node>> &nodes) {
      clearLights();
      if (!lighting) return;
      size_t before = lightEntities.size();
      for (const auto &n : nodes) collectLights(n.get());
      if (lightEntities.size() == before)   // no scene lights → default key light
        addDirectional({-0.4f, -1.0f, -0.6f}, {1.0f, 0.98f, 0.95f},
                       90000.0f * exposure, false);
    }

    // Expand triangles + quads into a non-indexed position+normal list, honouring
    // the node's smooth/flat shading (mirrors the GL backend's GeomCache).
    void expand(const GeometryNode *geom, std::vector<flm::float3> &P,
                std::vector<flm::float3> &N) {
      const auto &verts = geom->getVertices();
      const auto &norms = geom->getNormals();
      const bool smooth = geom->getSmoothShading();
      auto emitTri = [&](int a, int b, int c, int na, int nb, int nc) {
        flm::float3 pa{verts[a][0], verts[a][1], verts[a][2]};
        flm::float3 pb{verts[b][0], verts[b][1], verts[b][2]};
        flm::float3 pc{verts[c][0], verts[c][1], verts[c][2]};
        flm::float3 fn = normalized(cross(pb - pa, pc - pa));
        auto nrm = [&](int ni) {
          if (smooth && ni >= 0 && ni < (int)norms.size())
            return flm::float3{norms[ni][0], norms[ni][1], norms[ni][2]};
          return fn;
        };
        P.push_back(pa); N.push_back(nrm(na));
        P.push_back(pb); N.push_back(nrm(nb));
        P.push_back(pc); N.push_back(nrm(nc));
      };
      if (geom->isPrimitiveVisible(PrimTriangle))
        for (const auto &t : geom->getTriangles())
          emitTri(t.v[0], t.v[1], t.v[2], t.n[0], t.n[1], t.n[2]);
      if (geom->isPrimitiveVisible(PrimQuad))
        for (const auto &q : geom->getQuads()) {
          emitTri(q.v[0], q.v[1], q.v[2], q.n[0], q.n[1], q.n[2]);
          emitTri(q.v[0], q.v[2], q.v[3], q.n[0], q.n[2], q.n[3]);
        }
    }

    void syncGeometry(GeometryNode *geom) {
      NodeCache &nc = cache[geom];
      const uint64_t v = geom->getGeometryVersion();
      if (nc.vb && nc.builtVersion == v) { updateMaterialAndTransform(geom, nc); return; }

      destroyCache(nc);   // rebuild: tear down old buffers/renderable, keep map slot

      std::vector<flm::float3> P, N;
      expand(geom, P, N);
      nc.builtVersion = v;
      const size_t nv = P.size();
      if (nv < 3) return;   // nothing solid to draw

      // Tangent frames (quaternions) — Filament derives the shading normal from
      // these for lit materials. normals-only is fine without normal maps.
      auto *so = fgeo::SurfaceOrientation::Builder()
                     .vertexCount((uint32_t)nv).normals(N.data()).build();
      auto *quatBuf = new flm::quatf[nv];
      so->getQuats(quatBuf, nv);
      delete so;

      // Heap copies handed to Filament (consumed asynchronously at flushAndWait,
      // after this function returns → pointers into locals would dangle).
      auto *posBuf = new flm::float3[nv];
      flm::float3 lo{1e30f, 1e30f, 1e30f}, hi{-1e30f, -1e30f, -1e30f};
      for (size_t i = 0; i < nv; ++i) {
        posBuf[i] = P[i];
        for (int k = 0; k < 3; ++k) { lo[k] = std::min(lo[k], P[i][k]); hi[k] = std::max(hi[k], P[i][k]); }
      }
      auto *idxBuf = new uint32_t[nv];
      for (uint32_t i = 0; i < nv; ++i) idxBuf[i] = i;

      auto freeF3 = [](void *p, size_t, void *) { delete[] static_cast<flm::float3 *>(p); };
      auto freeQ = [](void *p, size_t, void *) { delete[] static_cast<flm::quatf *>(p); };
      auto freeU32 = [](void *p, size_t, void *) { delete[] static_cast<uint32_t *>(p); };

      nc.vb = fl::VertexBuffer::Builder()
          .vertexCount((uint32_t)nv).bufferCount(2)
          .attribute(fl::VertexAttribute::POSITION, 0,
                     fl::VertexBuffer::AttributeType::FLOAT3, 0, sizeof(flm::float3))
          .attribute(fl::VertexAttribute::TANGENTS, 1,
                     fl::VertexBuffer::AttributeType::FLOAT4, 0, sizeof(flm::quatf))
          .build(*engine);
      nc.vb->setBufferAt(*engine, 0, fl::VertexBuffer::BufferDescriptor(
          posBuf, nv * sizeof(flm::float3), freeF3));
      nc.vb->setBufferAt(*engine, 1, fl::VertexBuffer::BufferDescriptor(
          quatBuf, nv * sizeof(flm::quatf), freeQ));

      nc.ib = fl::IndexBuffer::Builder()
          .indexCount((uint32_t)nv)
          .bufferType(fl::IndexBuffer::IndexType::UINT).build(*engine);
      nc.ib->setBuffer(*engine, fl::IndexBuffer::BufferDescriptor(
          idxBuf, nv * sizeof(uint32_t), freeU32));

      nc.mi = lit->createInstance();

      nc.entity = ::utils::EntityManager::get().create();
      fl::RenderableManager::Builder(1)
          .boundingBox({{(lo[0] + hi[0]) * 0.5f, (lo[1] + hi[1]) * 0.5f, (lo[2] + hi[2]) * 0.5f},
                        {(hi[0] - lo[0]) * 0.5f + 1, (hi[1] - lo[1]) * 0.5f + 1, (hi[2] - lo[2]) * 0.5f + 1}})
          .material(0, nc.mi)
          .geometry(0, fl::RenderableManager::PrimitiveType::TRIANGLES, nc.vb, nc.ib, 0, nv)
          .castShadows(true).receiveShadows(true)
          .culling(false)
          .build(*engine, nc.entity);
      engine->getTransformManager().create(nc.entity);
      fscene->addEntity(nc.entity);
      nc.inScene = true;

      updateMaterialAndTransform(geom, nc);
    }

    void updateMaterialAndTransform(GeometryNode *geom, NodeCache &nc) {
      if (!nc.entity) return;
      auto mat = geom->getMaterial();
      cv3d::GeomColor bc = mat ? mat->baseColor : cv3d::GeomColor{0.78f, 0.78f, 0.78f, 1.0f};
      float metallic = mat ? mat->metallic : 0.0f;
      float roughness = mat ? mat->roughness : 0.6f;
      cv3d::GeomColor em = mat ? mat->emissive : cv3d::GeomColor{0, 0, 0, 1};
      if (nc.mi) {
        nc.mi->setParameter("baseColor", flm::float3{bc[0], bc[1], bc[2]});
        nc.mi->setParameter("metallic", metallic);
        nc.mi->setParameter("roughness", std::max(0.045f, roughness));
        nc.mi->setParameter("emissive", flm::float3{em[0], em[1], em[2]});
      }
      auto &tm = engine->getTransformManager();
      tm.setTransform(tm.getInstance(nc.entity),
                      toFilament(geom->getTransformation(true)));
    }

    void syncNode(Node *node) {
      if (!node || !node->isVisible()) return;
      if (dynamic_cast<LightNode *>(node)) return;   // lights handled in syncLights
      if (auto *g = dynamic_cast<GroupNode *>(node)) {
        for (int i = 0; i < g->getChildCount(); ++i) syncNode(g->getChild(i));
        return;
      }
      if (auto *geom = dynamic_cast<GeometryNode *>(node)) syncGeometry(geom);
    }
  };

  FilamentRenderBackend::FilamentRenderBackend() : m_data(std::make_unique<Data>()) {
    m_data->engine = fl::Engine::create(fl::Engine::Backend::METAL);
    if (!m_data->engine) return;   // isValid() == false
    m_data->renderer = m_data->engine->createRenderer();
    m_data->view = m_data->engine->createView();
    m_data->fscene = m_data->engine->createScene();
    m_data->camEntity = ::utils::EntityManager::get().create();
    m_data->fcam = m_data->engine->createCamera(m_data->camEntity);
    m_data->view->setScene(m_data->fscene);
    m_data->view->setCamera(m_data->fcam);
    m_data->lit = fl::Material::Builder()
        .package(LIT_PBR_FILAMAT, sizeof(LIT_PBR_FILAMAT)).build(*m_data->engine);
    m_data->unlit = fl::Material::Builder()
        .package(UNLIT_SOLID_FILAMAT, sizeof(UNLIT_SOLID_FILAMAT)).build(*m_data->engine);

    // Constant ambient environment (SH L0 only) so surfaces facing away from the
    // key light aren't pure black — the Filament analogue of the GL ambient env.
    flm::float3 amb{1.0f, 1.0f, 1.0f};
    m_data->ibl = fl::IndirectLight::Builder().irradiance(1, &amb).intensity(30000.0f)
        .build(*m_data->engine);
    m_data->fscene->setIndirectLight(m_data->ibl);
  }

  FilamentRenderBackend::~FilamentRenderBackend() {
    if (!m_data->engine) return;
    m_data->clearCache();
    m_data->clearLights();
    fl::Engine *e = m_data->engine;
    if (m_data->ibl) e->destroy(m_data->ibl);
    if (m_data->lit) e->destroy(m_data->lit);
    if (m_data->unlit) e->destroy(m_data->unlit);
    if (m_data->fcam) e->destroyCameraComponent(m_data->camEntity);
    if (m_data->camEntity) ::utils::EntityManager::get().destroy(m_data->camEntity);
    if (m_data->view) e->destroy(m_data->view);
    if (m_data->fscene) e->destroy(m_data->fscene);
    if (m_data->renderer) e->destroy(m_data->renderer);
    if (m_data->swapChain) e->destroy(m_data->swapChain);
    fl::Engine::destroy(&e);
  }

  bool FilamentRenderBackend::isValid() const { return m_data->engine != nullptr; }

  void FilamentRenderBackend::setTargetSize(const utils::Size &size) {
    m_data->targetSize = size;
  }
  utils::Size FilamentRenderBackend::getTargetSize() const { return m_data->targetSize; }

  bool FilamentRenderBackend::readColor(core::Img8u &dst) const {
    if (!m_data->engine || m_data->colorRGBA.empty()) return false;
    const int W = m_data->colorSize.width, H = m_data->colorSize.height;
    dst.setChannels(3);
    dst.setSize(m_data->colorSize);
    core::Channel8u r = dst[0], g = dst[1], b = dst[2];
    const uint8_t *p = m_data->colorRGBA.data();
    for (int y = 0; y < H; ++y)
      for (int x = 0; x < W; ++x) {
        const uint8_t *px = p + (size_t(y) * W + x) * 4;  // row 0 = top
        r(x, y) = px[0]; g(x, y) = px[1]; b(x, y) = px[2];
      }
    return true;
  }

  void FilamentRenderBackend::render(const std::vector<std::shared_ptr<Node>> &nodes,
                                     const Mat &viewMatrix,
                                     const Mat &projectionMatrix) {
    if (!m_data->engine) return;
    m_data->ensureSwapChain();
    const int W = m_data->targetSize.width, H = m_data->targetSize.height;
    if (W <= 0 || H <= 0) return;

    // Inject ICL's calibrated projection + camera placement (the P2 recipe), and a
    // neutral physical exposure the light intensities are calibrated against.
    m_data->fcam->setCustomProjection(toFilament(projectionMatrix), 1.0, 100000.0);
    m_data->fcam->setModelMatrix(toFilament(viewMatrix.inv()));
    m_data->fcam->setExposure(16.0f, 1.0f / 125.0f, 100.0f);   // sunny-16

    m_data->syncLights(nodes);
    for (const auto &n : nodes) m_data->syncNode(n.get());

    m_data->colorRGBA.assign(size_t(W) * H * 4, 0);
    if (m_data->renderer->beginFrame(m_data->swapChain)) {
      m_data->renderer->render(m_data->view);
      m_data->renderer->readPixels(0, 0, W, H, fl::backend::PixelBufferDescriptor(
          m_data->colorRGBA.data(), m_data->colorRGBA.size(),
          fl::backend::PixelDataFormat::RGBA, fl::backend::PixelDataType::UBYTE));
      m_data->renderer->endFrame();
    }
    m_data->engine->flushAndWait();   // buffer descriptors consumed here
    m_data->colorSize = m_data->targetSize;
  }

  void FilamentRenderBackend::setExposure(float e) { m_data->exposure = e; }
  void FilamentRenderBackend::setAmbient(float a) { m_data->ambient = a; }
  void FilamentRenderBackend::setOverlayAlpha(float a) { m_data->overlayAlpha = a; }
  void FilamentRenderBackend::setSSREnabled(bool e) { m_data->ssr = e; }
  bool FilamentRenderBackend::isSSREnabled() const { return m_data->ssr; }
  void FilamentRenderBackend::setShadowsEnabled(bool e) { m_data->shadows = e; }
  void FilamentRenderBackend::setLightingEnabled(bool e) { m_data->lighting = e; }
  void FilamentRenderBackend::setSkyEnabled(bool e) { m_data->sky = e; }
  void FilamentRenderBackend::setSkyUp(float, float, float) {}
  void FilamentRenderBackend::setDebugMode(int m) { m_data->debugMode = m; }
  void FilamentRenderBackend::invalidateCache() { if (m_data->engine) m_data->clearCache(); }
  void FilamentRenderBackend::flushInvalidatedCache() {}

} // namespace icl::viz3d
