// SPDX-License-Identifier: LGPL-3.0-or-later
// ICL - Image Component Library (https://github.com/iclcv/icl)
// Copyright (C) 2006-2026 Christof Elbrechter

// P2 projection-parity gate (the Filament backend linchpin, see filament-plan.md).
//
// Proves that ICL's calibrated cv3d::Camera maps into Filament clip space 1:1:
// a set of known 3D world points, rendered by Filament with the camera's
// projection injected via setCustomProjection, must rasterize to the exact
// pixels that cam.project(p) returns. The camera uses a REAL principal-point
// offset (not centered) so the row-3/col-3 & offset conventions are actually
// exercised (cf. project_pose_estimation_bugs).
//
// Mapping (resolved during S101 de-risking): Filament setCustomProjection wants
// the OpenGL NDC convention ([-1,1]^3), which is exactly what
// cv3d::Camera::getProjectionMatrixGL() already emits. So:
//   - Filament projection      = getProjectionMatrixGL(), transposed to column-major
//   - Filament camera model mtx = inverse(getCSTransformationMatrixGL())  (camera->world)
// Filament readPixels returns rows bottom-to-top (GL convention); cam.project
// returns image coords y-down from the top, so the expected readback row is
// (H-1 - py).
//
// Runs headless in-sandbox (Metal). No FilamentRenderBackend class yet — this is
// the gate that must be green before that class is built.

#include <filament/Camera.h>
#include <filament/Engine.h>
#include <filament/IndexBuffer.h>
#include <filament/Material.h>
#include <filament/MaterialInstance.h>
#include <filament/RenderableManager.h>
#include <filament/Renderer.h>
#include <filament/Scene.h>
#include <filament/SwapChain.h>
#include <filament/VertexBuffer.h>
#include <filament/View.h>
#include <filament/Viewport.h>
#include <filament/Box.h>

#include <backend/PixelBufferDescriptor.h>
#include <math/mat4.h>
#include <math/vec3.h>
#include <utils/EntityManager.h>

#include <icl/cv3d/Camera.h>

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <vector>

using namespace filament;
using IclCamera = icl::cv3d::Camera;   // filament also has a Camera — keep them distinct
using icl::cv3d::Mat;
using icl::cv3d::Vec;
using icl::utils::Point32f;

// Embedded compiled unlit material (matc -f header, generated by meson).
static const uint8_t UNLIT_SOLID_FILAMAT[] = {
#include "unlit_solid.filamat.h"
};

namespace {
  // ICL row-major Mat -> Filament column-major mat4.
  math::mat4 toFilament(const Mat &m) {
    math::mat4 f;  // identity
    for (int c = 0; c < 4; ++c)
      for (int r = 0; r < 4; ++r)
        f[c][r] = m(r, c);
    return f;
  }
}

int main() {
  // --- ICL camera with a real (off-centre) principal point ---
  IclCamera::RenderParams rp;
  rp.chipSize = {640, 480};
  rp.clipZNear = 1.0f;
  rp.clipZFar = 10000.0f;
  IclCamera cam;
  cam.setRenderParams(rp);
  cam.setPrincipalPointOffset(340.0f, 250.0f);   // NOT centred (320,240)
  const int W = rp.chipSize.width, H = rp.chipSize.height;

  // 3x3 grid of world points in the z=0 plane, in front of the camera
  // (default cam pos (0,0,10) looking toward -z).
  std::vector<Vec> worldPts;
  for (int gy = -1; gy <= 1; ++gy)
    for (int gx = -1; gx <= 1; ++gx)
      worldPts.emplace_back(gx * 2.0f, gy * 2.0f, 0.0f, 1.0f);
  const int N = (int)worldPts.size();

  // Ground truth: where ICL says each point lands (image coords, y-down).
  std::vector<Point32f> expected = cam.project(worldPts);

  // --- Filament setup (headless) ---
  Engine *engine = Engine::create(Engine::Backend::METAL);
  if (!engine) { std::fprintf(stderr, "parity: Engine::create failed\n"); return 2; }
  SwapChain *swapChain = engine->createSwapChain(W, H, SwapChain::CONFIG_READABLE);
  Renderer *renderer = engine->createRenderer();
  View *view = engine->createView();
  Scene *scene = engine->createScene();
  utils::Entity camEntity = utils::EntityManager::get().create();
  filament::Camera *fcam = engine->createCamera(camEntity);

  view->setScene(scene);
  view->setCamera(fcam);
  view->setViewport({0, 0, (uint32_t)W, (uint32_t)H});
  view->setPostProcessingEnabled(false);   // no tonemap/bloom — keep points crisp & white

  Renderer::ClearOptions co;
  co.clearColor = {0, 0, 0, 1};
  co.clear = true;
  renderer->setClearOptions(co);

  // Inject ICL's calibrated projection + view the way the real backend will:
  // projection = getProjectionMatrixGL() (GL NDC convention, as-is), and the
  // camera is *positioned* in the world via setModelMatrix(camera->world) =
  // inverse(getCSTransformationMatrixGL()). Filament then computes
  // clip = projection * inverse(model) * world = projGL * viewGL * world.
  fcam->setCustomProjection(toFilament(cam.getProjectionMatrixGL()),
                            rp.clipZNear, rp.clipZFar);
  fcam->setModelMatrix(toFilament(cam.getCSTransformationMatrixGL().inv()));

  // Material (unlit solid white).
  Material *material = Material::Builder()
      .package(UNLIT_SOLID_FILAMAT, sizeof(UNLIT_SOLID_FILAMAT))
      .build(*engine);
  MaterialInstance *mi = material->createInstance();
  mi->setParameter("color", math::float3{1.0f, 1.0f, 1.0f});

  // One tiny world-space triangle per point (centroid = the point). Filament
  // POINTS have no reliable size on Metal (undefined gl_PointSize), so we use a
  // small equilateral marker and take the lit-blob centroid — sub-pixel and
  // robust. Offset r is tiny (0.04 world units at depth ~10 → ~2px), so the
  // projected centroid equals the point's projection to well under a pixel.
  const float r = 0.04f;
  const float off[3][2] = {{0.0f, r}, {-0.866f * r, -0.5f * r}, {0.866f * r, -0.5f * r}};
  std::vector<math::float3> pos(N * 3);
  for (int i = 0; i < N; ++i)
    for (int k = 0; k < 3; ++k)
      pos[i * 3 + k] = {worldPts[i][0] + off[k][0],
                        worldPts[i][1] + off[k][1], worldPts[i][2]};
  std::vector<uint32_t> idx(N * 3);
  for (int i = 0; i < N * 3; ++i) idx[i] = i;

  VertexBuffer *vb = VertexBuffer::Builder()
      .vertexCount(N * 3).bufferCount(1)
      .attribute(VertexAttribute::POSITION, 0,
                 VertexBuffer::AttributeType::FLOAT3, 0, sizeof(math::float3))
      .build(*engine);
  vb->setBufferAt(*engine, 0,
      VertexBuffer::BufferDescriptor(pos.data(), N * 3 * sizeof(math::float3), nullptr));

  IndexBuffer *ib = IndexBuffer::Builder()
      .indexCount(N * 3).bufferType(IndexBuffer::IndexType::UINT).build(*engine);
  ib->setBuffer(*engine,
      IndexBuffer::BufferDescriptor(idx.data(), N * 3 * sizeof(uint32_t), nullptr));

  utils::Entity renderable = utils::EntityManager::get().create();
  RenderableManager::Builder(1)
      .boundingBox({{0, 0, 0}, {100, 100, 100}})
      .material(0, mi)
      .geometry(0, RenderableManager::PrimitiveType::TRIANGLES, vb, ib, 0, N * 3)
      .culling(false)
      .build(*engine, renderable);
  scene->addEntity(renderable);

  // --- Render + readback ---
  std::vector<uint8_t> px(size_t(W) * H * 4, 0);
  if (renderer->beginFrame(swapChain)) {
    renderer->render(view);
    renderer->readPixels(0, 0, W, H, backend::PixelBufferDescriptor(
        px.data(), px.size(),
        backend::PixelDataFormat::RGBA, backend::PixelDataType::UBYTE));
    renderer->endFrame();
  } else {
    std::fprintf(stderr, "parity: beginFrame false\n"); return 3;
  }
  engine->flushAndWait();

  // Readback row 0 = top (empirically verified — matches cam.project directly,
  // no y-flip). Greedy-cluster the lit pixels into blobs; each blob's centroid is
  // a rendered marker's sub-pixel centre.
  struct P { float x, y; };
  std::vector<P> raw;
  for (int row = 0; row < H; ++row)
    for (int col = 0; col < W; ++col) {
      const uint8_t *p = &px[(size_t(row) * W + col) * 4];
      if (p[0] > 128 || p[1] > 128 || p[2] > 128) raw.push_back({(float)col, (float)row});
    }
  std::vector<P> blobs;
  {
    std::vector<char> used(raw.size(), 0);
    for (size_t i = 0; i < raw.size(); ++i) {
      if (used[i]) continue;
      float sx = 0, sy = 0; int n = 0;
      for (size_t j = 0; j < raw.size(); ++j)
        if (!used[j] && std::abs(raw[j].x - raw[i].x) < 8 && std::abs(raw[j].y - raw[i].y) < 8) {
          used[j] = 1; sx += raw[j].x; sy += raw[j].y; ++n;
        }
      blobs.push_back({sx / n, sy / n});
    }
  }

  // Match each expected projection to the nearest blob centroid; track worst err.
  float maxErr = 0.0f;
  int matched = 0;
  for (int i = 0; i < N; ++i) {
    float best = 1e9f;
    for (const auto &b : blobs) {
      float dx = b.x - expected[i].x, dy = b.y - expected[i].y;
      best = std::min(best, std::sqrt(dx * dx + dy * dy));
    }
    std::printf("parity: pt%d expected(%.2f,%.2f) err=%.2fpx\n",
                i, expected[i].x, expected[i].y, best);
    if (best < 1.0f) ++matched;
    maxErr = std::max(maxErr, best);
  }
  std::printf("parity: %d blobs, %d/%d points within 1px, maxErr=%.2fpx\n",
              (int)blobs.size(), matched, N, maxErr);

  engine->destroy(renderable);
  engine->destroy(vb);
  engine->destroy(ib);
  engine->destroy(mi);
  engine->destroy(material);
  utils::EntityManager::get().destroy(camEntity);
  engine->destroyCameraComponent(camEntity);
  engine->destroy(view);
  engine->destroy(scene);
  engine->destroy(renderer);
  engine->destroy(swapChain);
  Engine::destroy(&engine);

  if (matched == N) {
    std::printf("parity: PASS — all %d points rasterize to cam.project (maxErr %.2fpx)\n",
                N, maxErr);
    return 0;
  }
  std::fprintf(stderr, "parity: FAIL — only %d/%d matched\n", matched, N);
  return 1;
}
