set(on ${ICL_XDEP_IPP_ON})
if(ICL_64BIT)
  icl_check_external_package(IPP ipp.h "ippcore;ippi;ipps;ippcv;ippm;ippcc" em64t/sharedlib em64t/include FALSE TRUE)
else()
  icl_check_external_package(IPP ipp.h "ippcore;ippi;ipps;ippcv;ippm;ippcc" sharedlib include FALSE TRUE)
endif()
if(NOT HAVE_IPP_COND AND ${on})
  set(ICL_XDEP_IPP_ON TRUE)
  if(ICL_64BIT)
    icl_check_external_package(IPP ipp.h "ippcore;ippi;ipps;ippcv;ippm;ippcc" ipp/lib/em64t ipp/em64t/include TRUE TRUE)
  else()
    icl_check_external_package(IPP ipp.h "ippcore;ippi;ipps;ippcv;ippm;ippcc;" ipp/lib/ia32 ipp/include TRUE TRUE)
  endif()
endif()
if(HAVE_IPP_COND)
  add_definitions( -DICL_USE_IPP_LIB)
  if(ICL_64BIT)
    link_directories(${ICL_XDEP_IPP_PATH}/lib/em64t)
  else()
    link_directories(${ICL_XDEP_IPP_PATH}/lib/ia32)
  endif()
endif()

