if(ICL_64BIT)
  icl_check_external_package(IPP ipp.h "ippcore;ippi;ipps;ippcv;ippm;ippcc" em64t/sharedlib em64t/include /vol/nivision/share/IPP/6.1-ia32 HAVE_IPP_COND TRUE)
else()
  icl_check_external_package(IPP ipp.h "ippcore;ippi;ipps;ippcv;ippm;ippcc" sharedlib include /vol/nivision/share/IPP/6.1-ia32 HAVE_IPP_COND TRUE)
endif()
if(HAVE_IPP_COND)
  if(ICL_VAR_USE_INTEL_OMP_IF_POSSIBLE)
    set(IPP_LIBS_l ippcore ippi ipps ippcv ippm ippcc iomp5)
    #    set(IPP_LIB_PATH "${ICL_XDEP_IPP_PATH}/${REL_LIB_DIR}")
  else()
    set(IPP_LIBS_l ippcore ippi ipps ippcv ippm ippcc)# guide iomp5)
  endif()
endif()
