if(ICL_64BIT)
  icl_check_external_package(PYLON "pylon/PylonIncludes.h;pylon/TransportLayer.h" "pylonbase;pylonutility;pylongigesupp" lib64 include TRUE TRUE)
else() 
  icl_simple_check_external_package(PYLON "pylon/PylonIncludes.h" "pylonbase;pylonutility;pylongigesupp")
endif()
