if(ICL_64BIT)
  icl_check_external_package(MKL "mkl_types.h;mkl_cblas.h" "mkl_intel_lp64;mkl_intel_thread;mkl_core" lib/em64t include /vol/nivision/share/MKL/10.2-ia32 HAVE_MKL_COND TRUE)
  if(HAVE_MKL_COND)
    if(ICL_VAR_USE_INTEL_OMP_IF_POSSIBLE)
      set(MKL_LIBS_l mkl_intel_lp64 mkl_intel_thread mkl_core iomp5)
    else()
      set(MKL_LIBS_l mkl_intel_lp64 mkl_intel_thread mkl_core)
    endif()
  endif()
else()  
  icl_check_external_package(MKL "mkl_types.h;mkl_cblas.h" "mkl_intel;mkl_intel_thread;mkl_core" lib/32 include /vol/nivision/share/MKL/10.2-ia32 HAVE_MKL_COND TRUE)
  if(HAVE_MKL_COND)
    if(ICL_VAR_USE_INTEL_OMP_IF_POSSIBLE)
      set(MKL_LIBS_l mkl_intel mkl_intel_thread mkl_core iomp5)
    else()
      set(MKL_LIBS_l mkl_intel mkl_intel_thread mkl_core)
    endif()
  endif()
endif()
