name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  linux_mac:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]

        include: # add specific configs
          # suppress cmake warnings
          - os: ubuntu-18.04
            cmake.args: -Wno-dev

          # build docs
          - os: ubuntu-latest
            docs: true

          # build with clang
          - os: ubuntu-latest
            clang: true

    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
    name: ${{ matrix.os }}${{ matrix.clang && ' • clang' || '' }}${{ matrix.docs && ' • docs' || ''}}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: ccache
      if: runner.os == 'Linux'
      uses: pat-s/always-upload-cache@v2.1.5
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ env.CACHE_PREFIX }}-${{ github.sha }}-${{ github.run_id }}
        restore-keys: >
          ${{ env.CACHE_PREFIX }}-${{ github.sha }}
          ${{ env.CACHE_PREFIX }}
      env:
        CACHE_PREFIX: ccache-${{ matrix.os }}${{ matrix.clang && '-clang' || '' }}

    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        DEBIAN_FRONTEND=noninteractive \
        sudo apt-get install -y \
          build-essential git cmake ccache python3-pip dirmngr \
          devscripts equivs apt-file debhelper sudo wget \
          libjpeg-dev libpng-dev ${{ matrix.compiler }} ca-certificates tzdata \
          doxygen graphviz python3-sphinx python3-sphinx-rtd-theme python3-pyparsing texlive-latex-base ghostscript
        # configure linux-specific build options
        echo ICL_OPTIONS="-DBUILD_REDIST=DEB" >> $GITHUB_ENV

    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        HOMEBREW_NO_AUTO_UPDATE=1 brew install iclcv/homebrew-formulas/icl --only-dependencies || true
        HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov glog
        # configure osx-specific build options
        echo ICL_OPTIONS=" \
          -DCMAKE_MODULE_PATH=/usr/local/share/cmake/Modules \
          -DOPENCV_ROOT=/usr/local/opt/opencv@3/share/OpenCV \
          -DQT_ROOT=/usr/local/opt/qt5 \
          " >> $GITHUB_ENV

    - name: Configure cmake
      env:
        CC: ${{ matrix.clang && 'clang' || 'cc' }}
        CXX: ${{ matrix.clang && 'clang++' || 'c++' }}
      run: >
        cmake -S . -B build
        -DCMAKE_INSTALL_PREFIX=/tmp/icl
        -DBUILD_EXAMPLES=ON
        -DBUILD_DEMOS=ON
        -DBUILD_APPS=ON
        -DBUILD_TESTS=ON
        -DBUILD_WITH_OPENCV=ON
        -DBUILD_WITH_QT=ON
        -DBUILD_WITH_OPENGL=ON
        -DBUILD_WITH_EIGEN3=ON
        -DBUILD_WITH_IMAGEMAGICK=ON
        -DBUILD_WITH_LIBAV=ON
        -DBUILD_WITH_LIBDC=ON
        -DBUILD_WITH_LIBFREENECT=ON
        -DBUILD_WITH_V4L=ON
        -DBUILD_WITH_LIBUSB=ON
        -DBUILD_WITH_ZMQ=ON
        -DBUILD_WITH_OPENCL=ON
        -DBUILD_WITH_OPENNI=ON
        -DBUILD_WITH_PCL=ON
        -DBUILD_WITH_BULLET=ON
        $ICL_OPTIONS
        ${{ matrix.cmake.args }}

    - name: Build
      run: cmake --build build -j3

    - name: Test
      run: cmake --build build --target test

    - name: Install
      run: cmake --build build --target install

    - name: Build docs
      if: matrix.docs
      run: cmake --build build --target pages

    - name: Deploy docs (from master only)
      if: matrix.docs && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/doc/pages


  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: # Take care to use matching versions!
          - msvc: 2019
            arch: 32
          - msvc: 2019
            qt: 5.15.2
            cv: 3.4.16
            package: true

    name: MSVC ${{ matrix.msvc }} • ${{ matrix.arch || '64' }}bit${{ matrix.qt && ' • Qt '}}${{ matrix.qt }}${{ matrix.cv && ' • OpenCV '}}${{ matrix.cv }}

    steps:
    - uses: actions/checkout@v2

    - name: Prepare MSVC
      uses: ilammy/msvc-dev-cmd@v1.9.0
      with:
        toolset: ${{ matrix.msvc == '2019' && '' || (matrix.msvc == '2015' && '14.0') || '' }}
        arch: win${{ matrix.arch || '64' }}

    - name: Install Qt
      if: matrix.qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        arch: win${{ matrix.arch || '64' }}_msvc${{ matrix.msvc }}_${{ matrix.arch || '64' }}

    - name: Define $DEPS folder
      run: |
        $DEPS = "$env:RUNNER_WORKSPACE\deps"
        mkdir $DEPS
        # Set $DEPS as environment variable for next steps too
        echo "DEPS=$DEPS" >> $env:GITHUB_ENV

    - name: Install pthreads
      run: |
        $base = "$env:DEPS\pthreads"
        Invoke-WebRequest http://ftp.gwdg.de/pub/linux/sources.redhat.com/pthreads-win32/pthreads-w32-2-9-1-release.zip -OutFile "$base.zip"
        7z x "$base.zip" -o"$base"

        $base = "$base\Pre-built.2"
        echo "-DPTHREADS_INCLUDE_DIR=$base\include" >> "$env:DEPS\opts"
        echo "-DpthreadVC2_LIBRARY=$base\lib\x${{ matrix.arch == '32' && '86' || '64' }}\pthreadVC2.lib" >> "$env:DEPS\opts"

    - name: Install GLEW
      run: |
        $base = "$env:DEPS\glew"
        Invoke-WebRequest -UserAgent Wget https://downloads.sourceforge.net/project/glew/glew/2.2.0/glew-2.2.0-win32.zip -OutFile "$base.zip"
        7z x "$base.zip" -o"$base"

        echo "-DGLEW_ROOT=$base\glew-2.2.0" >> "$env:DEPS\opts"

    - name: Install OpenCV
      if: matrix.cv && matrix.arch != '32'  # OpenCV doesn't ship a 32bit version anymore
      run: |
        choco install opencv --version ${{ matrix.cv }}

        echo "-DBUILD_WITH_OPENCV=ON" >> "$env:DEPS\opts"
        echo "-DOPENCV_ROOT=C:\tools\opencv\build" >> "$env:DEPS\opts"

    - name: Show extra cmake options
      run: cat "$env:DEPS\opts"

    - name: Configure cmake
      run: >
        cmake -S . -B build -G "NMake Makefiles"
        -DBUILD_EXAMPLES=ON
        -DBUILD_DEMOS=ON
        -DBUILD_APPS=ON
        -DBUILD_TESTS=ON
        -DBUILD_REDIST=WIX
        -DBUILD_WITH_QT=${{ matrix.qt && 'ON' || 'OFF' }}
        (Get-Content "$env:DEPS\opts")

    - name: Build
      run: cmake --build build -j3

    - name: Test
      if: false  # Tests fail with exit code 0xc0000135
      run: cmake --build build --target test

    - name: Package
      if: matrix.package
      run: cmake --build build --target package

    - name: Upload *.msi
      if: matrix.package
      uses: actions/upload-artifact@v2
      with:
        name: msi-installer-win${{ matrix.arch || '64' }}${{ matrix.qt && '-Qt'}}${{ matrix.qt }}${{ matrix.cv && '-OpenCV'}}${{ matrix.cv }}
        path: build\_CPack_Packages\*\WIX\icl-*.msi
